#!/usr/bin/env bash
#
# Tests the artifacts generated by install/setup-bluetooth.sh via --emit, which
# needs no root and touches no system state. Safe on a development machine.
#
# Two shellcheck rules are off for the whole file, both because of what this
# suite is:
#   SC2016  most assertions grep the GENERATED arbiter for literal text like
#           "$AUDIO_UNIT". The dollar sign is the thing being asserted; expanding
#           it here would search for this shell's value instead.
#   SC2034  RFKILL_ROOT and DRY_RUN look unused because they are read by
#           functions sourced out of setup-bluetooth.sh, which the linter cannot
#           see through. Same reason test-setup-helpers.sh carries this pragma.
# shellcheck disable=SC2016,SC2034
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO/install/setup-bluetooth.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0; FAIL=0
check() {
    if [[ "$2" == "$3" ]]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$1"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s\n       expected: %q\n       actual:   %q\n' "$1" "$2" "$3"
    fi
}
banner() { printf '\n== %s ==\n' "$1"; }
has()    { grep -qF -- "$1" "$2"; echo $?; }
hasre()  { grep -qE -- "$1" "$2"; echo $?; }
count()  { grep -cF -- "$1" "$2"; }

# Grep only lines that are NOT shell comments.
#
# Use this for any "X must not appear" assertion. Every generated artifact in
# this repo explains itself, so a whole-file grep for a thing the script
# deliberately AVOIDS matches the explanation and passes when it should fail.
# That has now cost three assertions in this suite alone; see decisions.md.
hascode() { grep -vE '^[[:space:]]*#' "$2" | grep -qE -- "$1"; echo $?; }

OUT="$WORK/emit"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "emit exits 0" "0" "$?"

# Every flag below is also NAMED in an explanatory comment in the generated
# block, so grepping the whole file proves nothing — it matches the prose that
# describes the flag rather than the flag itself. Pull out the two assignment
# lines and assert against those. This repo has paid for that mistake before
# (decisions.md), and it survived a mutation here before this was tightened.
optline()   { grep -E '^ExecStart=.*/bluealsa( |$)' "$OVERRIDE" | head -1; }
aplayline() { grep -E '^ExecStart=.*/bluealsa-aplay' "$AUDIO" | head -1; }
inopt()     { printf '%s' "$(optline)"   | grep -qF -- "$1"; echo $?; }
inaplay()   { printf '%s' "$(aplayline)" | grep -qF -- "$1"; echo $?; }

ARBITER="$OUT/musicbox-bt"
MONITOR="$OUT/musicbox-bt-monitor.service"
AUDIO="$OUT/musicbox-bt-audio.service"
AGENT="$OUT/musicbox-bt-agent.service"
MAINBLOCK="$OUT/main.conf.block"
OVERRIDE="$OUT/bluealsa-override.conf"
for f in "$ARBITER" "$MONITOR" "$AUDIO" "$AGENT" "$MAINBLOCK" "$OVERRIDE"; do
    check "$(basename "$f") written" "0" "$(if [[ -f "$f" ]]; then echo 0; else echo 1; fi)"
done

banner "THE DAC CONTRACT — MPD AND BLUETOOTH MUST NEVER BOTH HOLD hw:0,0"
# The device is opened raw, with no dmix and no sound server, so this is a hard
# exclusion. bluealsa-aplay does NOT retry a busy device, so every one of these
# orderings is the difference between a handoff and silence.

# Ordering is asserted on the generated text, because that is where it lives.
pause_at="$(grep -n 'mpc pause' "$ARBITER" | head -1 | cut -d: -f1)"
wait_at="$(grep -n 'wait_for_dac ||' "$ARBITER" | head -1 | cut -d: -f1)"
start_at="$(grep -n 'systemctl start "\$AUDIO_UNIT"' "$ARBITER" | head -1 | cut -d: -f1)"
check "the arbiter pauses MPD before waiting" "0" \
    "$(if [[ -n "$pause_at" && -n "$wait_at" && "$pause_at" -lt "$wait_at" ]]; then echo 0; else echo 1; fi)"
check "the arbiter waits for the card before starting the audio unit" "0" \
    "$(if [[ -n "$wait_at" && -n "$start_at" && "$wait_at" -lt "$start_at" ]]; then echo 0; else echo 1; fi)"

# The reverse handoff.
disc_at="$(grep -n 'bluetoothctl disconnect "\$addr"' "$ARBITER" | head -1 | cut -d: -f1)"
rel_at="$(grep -n '^    release_bluetooth$' "$ARBITER" | head -1 | cut -d: -f1)"
toggle_at="$(grep -n 'mpc disable 1' "$ARBITER" | head -1 | cut -d: -f1)"
mpdwait_at="$(grep -n 'wait_for_aplay ||' "$ARBITER" | head -1 | cut -d: -f1)"
check "MPD's turn: disconnect comes before releasing the audio unit" "0" \
    "$(if [[ -n "$disc_at" && -n "$rel_at" && "$disc_at" -lt "$rel_at" ]]; then echo 0; else echo 1; fi)"
check "MPD's turn: the toggle comes AFTER our player has exited" "0" \
    "$(if [[ -n "$mpdwait_at" && -n "$toggle_at" && "$mpdwait_at" -lt "$toggle_at" ]]; then echo 0; else echo 1; fi)"
check "the output toggle re-enables as well as disables" "0" "$(has 'mpc enable 1' "$ARBITER")"
# Measured on the device: MPD, told to play while bluealsa held the card, logs
# "Failed to open audio output" and PAUSES ITSELF. Freeing the card is not enough
# — without this the user presses play and gets silence, with MPD showing paused.
play_at="$(grep -n 'mpc play' "$ARBITER" | head -1 | cut -d: -f1)"
check "MPD is actually restarted, not just unblocked" "0" "$(has 'mpc play' "$ARBITER")"
check "the play comes after the output toggle" "0" \
    "$(if [[ -n "$toggle_at" && -n "$play_at" && "$toggle_at" -lt "$play_at" ]]; then echo 0; else echo 1; fi)"
# It waits for OUR player to exit, not for the card to go quiet. Conflating those
# broke the reverse handoff: MPD is supposed to END UP holding the card, so
# waiting for it to be free waits for the wrong thing and then fires a corrective
# action on a box that was about to be fine.
check "MPD's turn waits for bluealsa-aplay, not for a free card" "0" "$(has 'wait_for_aplay' "$ARBITER")"
check "take_for_mpd does not wait for the card to be free" "1" \
    "$(sed -n '/^take_for_mpd()/,/^}/p' "$ARBITER" | grep -qE '^[[:space:]]*wait_for_dac'; echo $?)"
# The forward direction is the opposite: there MPD must genuinely let go first.
check "the phone's turn DOES wait for the card to be free" "0" \
    "$(sed -n '/^take_for_bluetooth()/,/^}/p' "$ARBITER" | grep -qE 'wait_for_dac'; echo $?)"

check "the arbiter is the only thing that starts the audio unit" "0" "$(has 'systemctl start "$AUDIO_UNIT"' "$ARBITER")"
check "the audio unit has NO [Install] section" "1" "$(hasre '^\[Install\]' "$AUDIO")"
check "the audio unit is not WantedBy anything" "1" "$(hasre '^WantedBy=' "$AUDIO")"
check "setup masks Debian's bluealsa-aplay.service" "0" "$(has 'systemctl mask bluealsa-aplay.service' "$SCRIPT")"
# mask prevents future starts and does NOTHING to a running instance, and apt
# both enables and starts that unit — so on a fresh box one is already running
# and competing for the DAC. Masking alone left it there until the next reboot.
check "and stops the running instance too" "0" "$(has 'systemctl stop bluealsa-aplay.service' "$SCRIPT")"
stop_at="$(grep -n 'systemctl stop bluealsa-aplay.service' "$SCRIPT" | head -1 | cut -d: -f1)"
mask_at="$(grep -n 'systemctl mask bluealsa-aplay.service' "$SCRIPT" | head -1 | cut -d: -f1)"
check "the stop comes before the mask" "0" \
    "$(if [[ -n "$stop_at" && -n "$mask_at" && "$stop_at" -lt "$mask_at" ]]; then echo 0; else echo 1; fi)"
check "revert unmasks it again" "0" "$(has 'systemctl unmask bluealsa-aplay.service' "$SCRIPT")"
check "bluealsa-aplay gets --single-audio" "0" "$(inaplay '--single-audio')"
check "the audio unit plays to the DAC, not to 'default'" "0" "$(inaplay '-D hw:0,0')"
check "the arbiter waits on the real PCM status file" "0" "$(has '/proc/asound/card0/pcm0p/sub0/status' "$ARBITER")"

banner "MPD is paused, never stopped, and never auto-resumed"
# pause keeps the queue position so the panel's play button resumes in place; a
# phone going out of range must not start the speaker playing to an empty room.
check "the arbiter pauses" "0" "$(has 'mpc pause' "$ARBITER")"
check "the arbiter never issues an mpc stop" "1" "$(hasre '^[[:space:]]*mpc stop' "$ARBITER")"
# `mpc play` IS issued, but only in take_for_mpd, where the user asked for it.
# The rule is that a phone wandering off must not start the speaker — so the
# release path specifically must never play.
check "the release path never starts playback" "1" \
    "$(sed -n '/^release_bluetooth()/,/^}/p' "$ARBITER" | grep -qE 'mpc (play|toggle)'; echo $?)"
check "nor does the disconnect handler" "1" \
    "$(sed -n '/^handle_bt()/,/^}/p' "$ARBITER" | grep -qE 'mpc (play|toggle)'; echo $?)"


banner "THE OPTIONS MUST ACTUALLY REACH THE DAEMON"
# This shipped wrong once. /etc/default/bluez-alsa exists on the system and is a
# DECOY: Debian's bluealsa.service has no EnvironmentFile and a hardcoded
# ExecStart, so a managed block there is read by nothing. The daemon ran with none
# of these options and every assertion below still passed, because they were
# checking a file rather than a command line.
check "the options are a systemd drop-in, not /etc/default" "0" "$(hasre '^\[Service\]' "$OVERRIDE")"
check "nothing is written to the decoy file" "1" \
    "$(hascode '/etc/default/bluez-alsa' "$SCRIPT")"
check "ExecStart is cleared before being set" "0" "$(hasre '^ExecStart=$' "$OVERRIDE")"
check "exactly one real ExecStart" "1" "$(grep -cE '^ExecStart=.+' "$OVERRIDE")"
# systemd APPENDS to list-valued directives, so without the empty reset the unit
# would carry Debian's ExecStart as well as ours and refuse to start.
reset_at="$(grep -n '^ExecStart=$' "$OVERRIDE" | head -1 | cut -d: -f1)"
set_at="$(grep -nE '^ExecStart=.+' "$OVERRIDE" | head -1 | cut -d: -f1)"
check "the reset comes first" "0" \
    "$(if [[ -n "$reset_at" && -n "$set_at" && "$reset_at" -lt "$set_at" ]]; then echo 0; else echo 1; fi)"
check "the audio unit names its own options, not an env var" "1" "$(hasre '\$APLAYOPTIONS' "$AUDIO")"
check "and reads no EnvironmentFile" "1" "$(hasre '^EnvironmentFile=' "$AUDIO")"

banner "codecs and volume"
# bluealsa enables ONLY SBC by default. Without these the codec work silently
# does not happen and every phone lands on plain SBC.
check "a2dp-sink, not a2dp-source" "0" "$(inopt '-p a2dp-sink')"
check "a2dp-source is not also requested" "1" "$(inopt '-p a2dp-source')"
check "aptX is enabled explicitly" "0" "$(inopt '-c aptX ')"
check "aptX HD is enabled explicitly" "0" "$(inopt '-c aptX-HD')"
check "SBC capabilities are raised to xq" "0" "$(inopt '--sbc-quality=xq')"
# Nothing on this box may attenuate: volume belongs to the preamp, and
# musicbox-dac-unity.service holds the DAC's gain stages at 0 dB.
check "the phone attenuates, not us (--a2dp-volume)" "0" "$(inopt '--a2dp-volume')"
check "bluealsa-aplay never touches the local mixer" "0" "$(inaplay '--volume=none')"
check "no software volume anywhere" "1" "$(inaplay '--volume=software')"
# LDAC is encode-only in Debian and no open-source decoder exists, so asking for
# it on a SINK would be cargo cult.
check "LDAC is not requested" "1" "$(inopt 'LDAC')"

banner "pairing works with no keyboard"
check "the adapter is named" "0" "$(has 'Name = musicbox' "$MAINBLOCK")"
# main.conf: "Only the major and minor device class bits are considered." BlueZ
# derives the service bits from the registered profiles, so writing them here
# would be decoration the running adapter contradicts (it reports 0x004c0414).
check "it advertises as an audio device, not class 0" "0" "$(has 'Class = 0x000414' "$MAINBLOCK")"
check "no decorative service-class bits" "1" \
    "$(hasre '^Class = 0x(0[1-9a-fA-F]|[1-9a-fA-F][0-9a-fA-F])0414' "$MAINBLOCK")"
check "discoverability never times out" "0" "$(has 'DiscoverableTimeout = 0' "$MAINBLOCK")"
check "pairability never times out" "0" "$(has 'PairableTimeout = 0' "$MAINBLOCK")"
check "always pairable" "0" "$(has 'AlwaysPairable = true' "$MAINBLOCK")"
check "the adapter powers on at boot" "0" "$(has 'AutoEnable = true' "$MAINBLOCK")"
check "the agent needs no input or display" "0" "$(has '--capability=NoInputNoOutput' "$AGENT")"

banner "the radio is unblocked, which is what the real box needed"
# Found soft-blocked on the device: bluetoothd logging "Failed to set mode:
# Failed (0x03)" every boot and the adapter reporting PowerState: off-blocked.
FAKE="$WORK/rfkill"
mkdir -p "$FAKE/rfkill0" "$FAKE/rfkill1" "$FAKE/rfkill2"
printf 'bluetooth' > "$FAKE/rfkill0/type"; printf 'hci0'  > "$FAKE/rfkill0/name"
printf '1' > "$FAKE/rfkill0/soft";         printf '0'     > "$FAKE/rfkill0/hard"
printf 'wlan'      > "$FAKE/rfkill1/type"; printf 'phy0'  > "$FAKE/rfkill1/name"
printf '0' > "$FAKE/rfkill1/soft";         printf '0'     > "$FAKE/rfkill1/hard"
# A second Bluetooth switch, hard-blocked: software cannot clear that and must
# say so rather than silently failing.
printf 'bluetooth' > "$FAKE/rfkill2/type"; printf 'hci1'  > "$FAKE/rfkill2/name"
printf '1' > "$FAKE/rfkill2/soft";         printf '1'     > "$FAKE/rfkill2/hard"

# Needs the real internal function, so source the script minus main.
HARNESS="$WORK/h.sh"
sed -e '$ d' \
    -e 's/^readonly \(MAIN_CONF\|DEFAULT_FILE\|ARBITER_BIN\|MONITOR_UNIT\|AUDIO_UNIT\|AGENT_UNIT\|STATE_DIR\|CONF_DIR\|RUN_DIR\|STATE_FILE\)=/\1=/' \
    "$SCRIPT" > "$HARNESS"
# shellcheck source=/dev/null
source "$HARNESS"
# The sourced script carries `set -euo pipefail`, which would now apply to THIS
# shell and abort the run on the first deliberately-failing assertion below.
set +e

RFKILL_ROOT="$FAKE"
DRY_RUN=0
unblock_bluetooth >/dev/null 2>&1
check "a soft-blocked Bluetooth radio is unblocked" "0" "$(cat "$FAKE/rfkill0/soft")"
check "wlan is left alone" "0" "$(cat "$FAKE/rfkill1/soft")"
check "a HARD-blocked radio is not pretended away" "1" "$(cat "$FAKE/rfkill2/soft")"
unblock_bluetooth >/dev/null 2>&1
check "running again is a no-op, not an error" "0" "$(cat "$FAKE/rfkill0/soft")"
DRY_RUN=1
printf '1' > "$FAKE/rfkill0/soft"
unblock_bluetooth >/dev/null 2>&1
check "--dry-run does not touch the radio" "1" "$(cat "$FAKE/rfkill0/soft")"
DRY_RUN=0

banner "managed block round-trip on a real fixture"
FIX="$WORK/main.conf"
printf '[General]\n#Name = BlueZ\n\n[Policy]\n#AutoEnable=false\n' > "$FIX"
out="$(write_managed_block "$FIX" "$(gen_mainconf_block)")"
cp "$out" "$FIX.new"; rm -f "$out"
check "exactly one opening marker" "1" "$(count '>>> musicbox setup-bluetooth.sh' "$FIX.new")"
check "closing marker is on its own line" "0" \
    "$(grep -qx '# <<< musicbox setup-bluetooth.sh managed block <<<' "$FIX.new"; echo $?)"
check "marker never glued to a setting" "1" "$(hasre '^[A-Za-z].*<<<' "$FIX.new")"
check "the original content survives" "0" "$(has '#Name = BlueZ' "$FIX.new")"
sum1="$(md5sum < "$FIX.new")"
out="$(write_managed_block "$FIX.new" "$(gen_mainconf_block)")"
check "re-writing over our own block is idempotent" "$sum1" "$(md5sum < "$out")"
stripped="$(strip_managed_block "$out")"
check "stripping restores the original" "$(md5sum < "$FIX")" "$(md5sum < "$stripped")"
rm -f "$out" "$stripped"

banner "the arbiter is a working program, not just text"
check "the generated arbiter parses" "0" "$(bash -n "$ARBITER"; echo $?)"
check "set -e is deliberately absent from a daemon" "1" "$(hasre '^set -euo' "$ARBITER")"
check "but it is still strict about unset vars" "0" "$(has 'set -uo pipefail' "$ARBITER")"

# Point a copy at a scratch state file and drive it for real.
RUNDIR="$WORK/run"
sed -e "s#^STATE_FILE=.*#STATE_FILE=\"$RUNDIR/bluetooth.json\"#" \
    -e "s#^RUN_DIR=.*#RUN_DIR=\"$RUNDIR\"#" "$ARBITER" > "$WORK/bt"
chmod +x "$WORK/bt"
check "publishing a device emits parseable JSON" \
    '{"name":"Pixel","address":"AA:BB:CC:DD:EE:FF","codec":"aptX HD"}' \
    "$(bash "$WORK/bt" publish 'Pixel' 'AA:BB:CC:DD:EE:FF' 'aptX HD')"
# Device names are user-chosen: quotes, backslashes and emoji all turn up, and an
# unescaped one would make the web server's parser return null — a phone that is
# connected but invisible in the UI.
check "a quote in the device name is escaped" \
    '{"name":"He said \"hi\"","address":"AA:BB:CC:DD:EE:FF"}' \
    "$(bash "$WORK/bt" publish 'He said "hi"' 'AA:BB:CC:DD:EE:FF')"
check "a backslash in the device name is escaped" \
    '{"name":"back\\slash","address":"AA:BB:CC:DD:EE:FF"}' \
    "$(bash "$WORK/bt" publish 'back\slash' 'AA:BB:CC:DD:EE:FF')"
check "an unnegotiated codec is omitted, not empty" \
    '{"name":"Pixel","address":"AA:BB:CC:DD:EE:FF"}' \
    "$(bash "$WORK/bt" publish 'Pixel' 'AA:BB:CC:DD:EE:FF')"
check "disconnected publishes an empty object" '{}' "$(bash "$WORK/bt" publish)"
check "status reads back what was published" '{}' "$(bash "$WORK/bt" status)"
check "status on a missing file still answers" '{}' \
    "$(rm -rf "$RUNDIR"; bash "$WORK/bt" status)"

banner "the state file path agrees with the web server"
# If these drift the UI silently never shows a device, with nothing else
# misbehaving — the same failure mode the album-art music root has.
check "the arbiter publishes where the server looks" "0" \
    "$(has "STATE_FILE=\"/run/musicbox/bluetooth.json\"" "$ARBITER")"
check "the server looks where the arbiter publishes" "0" \
    "$(has "DEFAULT_STATE_PATH = '/run/musicbox/bluetooth.json'" "$REPO/src/backend/src/bluetooth.ts")"
check "the run directory is created by systemd, not by hand" "0" "$(has 'RuntimeDirectory=musicbox' "$MONITOR")"
check "and is readable by the unprivileged server" "0" "$(has 'RuntimeDirectoryMode=0755' "$MONITOR")"
# Writing in place would let the server read a half-written document.
check "the arbiter publishes by rename" "0" "$(hasre 'mv -f "\$tmp" "\$STATE_FILE"' "$ARBITER")"

banner "THE CONTROL CHANNEL — the web UI's only way in"
# The backend cannot spawn busctl (asserted below), so it writes one verb into a
# FIFO the arbiter reads. Everything here is about that channel not silently
# failing, because a button that does nothing is the failure mode.
check "the arbiter creates the control FIFO" "0" "$(has 'mkfifo -m 0620 "$CONTROL_FIFO"' "$ARBITER")"
check "it is group-owned so the unprivileged server can write" "0" "$(has 'chgrp "$CONTROL_GROUP"' "$ARBITER")"
# `cat` on a FIFO returns EOF when the last writer closes, so without our own
# descriptor every command would end the feed and the restart loop would leave a
# two-second window where the next press gets ENXIO — intermittently dead buttons.
check "the arbiter holds the FIFO open itself" "0" "$(hasre '^[[:space:]]*exec 9<>"\$CONTROL_FIFO"' "$ARBITER")"
hold_at="$(grep -n 'exec 9<>' "$ARBITER" | head -1 | cut -d: -f1)"
feed_at="$(grep -n 'feed ctl' "$ARBITER" | head -1 | cut -d: -f1)"
check "it is held open BEFORE the feed starts reading" "0" \
    "$(if [[ -n "$hold_at" && -n "$feed_at" && "$hold_at" -lt "$feed_at" ]]; then echo 0; else echo 1; fi)"
check "a stale FIFO is replaced, not reused" "0" "$(hasre '^[[:space:]]*rm -f "\$CONTROL_FIFO"' "$ARBITER")"
check "the control feed is dispatched" "0" "$(has 'ctl)  handle_ctl' "$ARBITER")"
check "revert removes the FIFO" "0" "$(has '"$CONTROL_FIFO"' "$SCRIPT")"

banner "every control verb the API can send has a handler"
# The other half of CONTROL_VERBS in src/backend/src/bluetooth.ts. A verb accepted
# by the API with no case arm here would be a button that silently does nothing.
for v in play pause stop next previous disconnect; do
    check "handle_ctl handles '$v'" "0" \
        "$(sed -n '/^handle_ctl()/,/^}/p' "$ARBITER" | grep -qE "^[[:space:]]*${v}\)"; echo $?)"
done
check "play maps to AVRCP Play" "0" \
    "$(sed -n '/^handle_ctl()/,/^}/p' "$ARBITER" | grep -qE '^[[:space:]]*play\).*avrcp_command Play'; echo $?)"
check "an unknown verb is dropped, not run" "0" \
    "$(sed -n '/^handle_ctl()/,/^}/p' "$ARBITER" | grep -qE '\*\).*ignoring unknown'; echo $?)"

banner "disconnect ends the session WITHOUT resuming MPD"
# The user's rule: handing the speaker back must not start playing to an empty
# room. take_for_mpd is the other path and it DOES play, because there the user
# asked for it — so the two must not be confused.
check "ctl_disconnect exists" "0" "$(hasre '^ctl_disconnect\(\)' "$ARBITER")"
check "it goes through release_bluetooth" "0" \
    "$(sed -n '/^ctl_disconnect()/,/^}/p' "$ARBITER" | grep -q 'release_bluetooth'; echo $?)"
check "it never starts MPD" "1" \
    "$(sed -n '/^ctl_disconnect()/,/^}/p' "$ARBITER" | grep -qE 'mpc (play|toggle)'; echo $?)"
check "it never touches the output toggle" "1" \
    "$(sed -n '/^ctl_disconnect()/,/^}/p' "$ARBITER" | grep -qE 'mpc (disable|enable)'; echo $?)"
check "disconnect routes to ctl_disconnect, not take_for_mpd" "1" \
    "$(sed -n '/^handle_ctl()/,/^}/p' "$ARBITER" | grep -qE 'disconnect\).*take_for_mpd'; echo $?)"

banner "AVRCP metadata"
check "the player path is discovered, not assumed to be player0" "0" \
    "$(sed -n '/^avrcp_path()/,/^}/p' "$ARBITER" | grep -qF 'player[0-9]*'; echo $?)"
check "all properties are read in one GetAll call" "0" "$(has 'GetAll s org.bluez.MediaPlayer1' "$ARBITER")"
# The obvious sed for busctl's nested JSON truncates at the first comma or quote
# inside a song title, which is most of them.
check "the JSON is parsed by python3, not sed" "0" \
    "$(sed -n '/^avrcp_read()/,/^}/p' "$ARBITER" | grep -q 'python3'; echo $?)"
check "preflight warns when python3 is missing" "0" "$(has 'python3 is missing' "$SCRIPT")"
# Rewriting the state file 1Hz would push an SSE frame to every client and repaint
# the panel every second, on the vc4 path that has hard-locked this board.
check "publishing is gated on a change signature" "0" "$(has 'LAST_AVRCP' "$ARBITER")"
check "position is excluded from that signature" "1" \
    "$(sed -n '/^avrcp_publish()/,/^}/p' "$ARBITER" | grep -qE 'local sig=.*\$\{position\}'; echo $?)"
check "the tick does nothing while nothing is connected" "0" \
    "$(sed -n '/^handle_tick()/,/^}/p' "$ARBITER" | grep -qE '\[\[ -n "\$ACTIVE_ADDR" \]\] \|\| return'; echo $?)"
check "a phone with no AVRCP player is still published" "0" \
    "$(sed -n '/^avrcp_publish()/,/^}/p' "$ARBITER" | grep -qE 'publish_device "\$name" "\$addr" "\$codec"$'; echo $?)"

banner "NO COVER ART IS INVENTED FOR BLUETOOTH"
# AVRCP cannot supply one: the phone advertises 1.6 but offers no OBEX channel,
# and BlueZ implements none. Borrowing one from the library by matching artist and
# album was considered and REJECTED — a near-miss shows a confidently wrong cover,
# and a missing cover is obvious where a wrong one is misinformation.
check "the arbiter never looks a track up in the library" "1" \
    "$(hascode 'mpc (find|search|list)' "$ARBITER")"
check "no Bluetooth path derives an art URI" "1" \
    "$(grep -rhE --include='*.ts' -v '^[[:space:]]*(//|\*|/\*)' "$REPO/src/backend/src/bluetooth.ts" \
        | grep -qE 'artUriFor|/api/art'; echo $?)"
check "trackFromBluetooth sets image to null" "0" \
    "$(grep -A12 'export function trackFromBluetooth' "$REPO/src/backend/src/mpd/bridge.ts" \
        | grep -qF 'image: null'; echo $?)"
check "the dead find() was not pressed into service" "1" \
    "$(grep -rhE --include='*.ts' -v '^[[:space:]]*(//|\*|/\*)' "$REPO/src/backend/src/" \
        | grep -qE '\.find\((quoteArg|.?(artist|album))'; echo $?)"

banner "the hints point at things that exist"
# The unit is musicbox-bt-monitor.service; the SyslogIdentifier is musicbox-bt.
# `journalctl -u musicbox-bt` matches no unit and prints "No entries" — which is
# exactly what the first version of this told people to run.
check "no hint tells you to journalctl a unit that does not exist" "1" \
    "$(grep -qE 'journalctl -u musicbox-bt( |-b|-f|$)' "$SCRIPT"; echo $?)"
check "the monitor unit is the one named in the hints" "0" "$(has 'journalctl -u musicbox-bt-monitor' "$SCRIPT")"

banner "the arbiter must outlive the web server"
# This independence is the entire reason the handoff is not in the backend.
check "the monitor is not ordered after musicbox-server" "1" "$(hasre '^After=.*musicbox-server' "$MONITOR")"
check "the monitor does not want musicbox-server" "1" "$(hasre '^(Wants|Requires)=.*musicbox-server' "$MONITOR")"
check "the monitor restarts if it dies" "0" "$(has 'Restart=always' "$MONITOR")"
# Two exclusions, both deliberate:
#   comment lines — bluetooth.ts EXPLAINS that it does not do this, and a naive
#     grep matches the explanation instead of a violation. This repo has already
#     paid for that mistake once; see decisions.md.
#   *.test.ts — the tests need mkfifo to stand up a control channel. The invariant
#     is about the code that ships in the bundle, which is what could reach the
#     audio path on the device.
check "the backend never shells out to the arbiter" "1" \
    "$(grep -rhE --include='*.ts' --exclude='*.test.ts' -v '^[[:space:]]*(//|\*|/\*)' \
        "$REPO/src/backend/src/" | grep -qE "child_process|execSync|spawn\("; echo $?)"

banner "it configures, it does not install"
check "no apt-get in setup-bluetooth.sh" "1" "$(hasre '^[[:space:]]*(run )?(env .*)?apt-get ' "$SCRIPT")"
check "install.sh installs bluez-alsa-utils" "0" "$(hasre '^[[:space:]]*bluez-alsa-utils' "$REPO/install/install.sh")"
check "install.sh installs bluez-tools" "0" "$(hasre '^[[:space:]]*bluez-tools' "$REPO/install/install.sh")"
# fdk-aac would be pointless without rebuilding bluez-alsa against it; having the
# library on disk changes nothing and would just look like AAC works.
check "libfdk-aac is not installed" "1" "$(hasre '^[[:space:]]*libfdk-aac' "$REPO/install/install.sh")"

banner "one marker per script"
# Three scripts write to config.txt and three now write managed blocks elsewhere;
# a shared marker means one script eats another's block.
for s in "$REPO"/install/setup-*.sh; do
    base="$(basename "$s")"
    check "$base owns its marker" "0" \
        "$(grep -q "musicbox ${base} managed block" "$s" || ! grep -q 'managed block' "$s"; echo $?)"
done
check "no other script mentions our marker" "1" \
    "$(grep -l 'setup-bluetooth.sh managed block' "$REPO"/install/*.sh | grep -qv 'setup-bluetooth.sh'; echo $?)"

banner "idempotency and CLI"
check "--emit must be silent" "" "$(bash "$SCRIPT" --emit "$WORK/silent" 2>&1 >/dev/null)"
sum1="$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "re-emitting is byte-identical" "$sum1" "$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit >/dev/null 2>&1
check "--emit without a destination fails" "1" "$?"
bash "$SCRIPT" --bogus >/dev/null 2>&1
check "unknown option fails" "1" "$?"
bash "$SCRIPT" --help >/dev/null 2>&1
check "--help exits 0" "0" "$?"
check "--help mentions --revert" "0" "$(bash "$SCRIPT" --help 2>/dev/null | grep -q -- '--revert'; echo $?)"
check "--help mentions --dry-run" "0" "$(bash "$SCRIPT" --help 2>/dev/null | grep -q -- '--dry-run'; echo $?)"
check "--revert without root fails" "1" "$(bash "$SCRIPT" --revert >/dev/null 2>&1; echo $?)"

printf '\n===============================\n passed: %d   failed: %d\n===============================\n' "$PASS" "$FAIL"
[[ "$FAIL" -eq 0 ]]
