#!/usr/bin/env bash
#
# Tests the artifacts generated by install/setup-mpd.sh via --emit, which needs
# no root, no MPD installed and no NAS. Safe on a development machine.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO/install/setup-mpd.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0; FAIL=0
check() {
    if [[ "$2" == "$3" ]]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$1"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s\n       expected: %q\n       actual:   %q\n' "$1" "$2" "$3"
    fi
}
banner() { printf '\n== %s ==\n' "$1"; }
has()    { grep -qF -- "$1" "$2"; echo $?; }
hasre()  { grep -qE -- "$1" "$2"; echo $?; }
count()  { grep -cF -- "$1" "$2"; }

OUT="$WORK/emit"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "emit exits 0" "0" "$?"

CONF="$OUT/mpd.conf"; DEFAULTS="$OUT/default-mpd"
check "mpd.conf written"    "0" "$(if [[ -f "$CONF" ]]; then echo 0; else echo 1; fi)"
check "default-mpd written" "0" "$(if [[ -f "$DEFAULTS" ]]; then echo 0; else echo 1; fi)"

banner "THE LIBRARY PATH (the regression this file exists to prevent)"
check "music_directory is /srv/music/Music" "0" \
    "$(hasre '^music_directory[[:space:]]+"/srv/music/Music"$' "$CONF")"
check "music_directory is NOT the bare share root" "1" \
    "$(hasre '^music_directory[[:space:]]+"/srv/music"$' "$CONF")"
check "exactly one music_directory" "1" "$(count 'music_directory  ' "$CONF")"
check "the reason is written down" "0" "$(has '#recycle' "$CONF")"

banner "audio output — card 0 is the DAC"
check "type alsa"              "0" "$(hasre '^[[:space:]]+type[[:space:]]+"alsa"$' "$CONF")"
check "device hw:0,0"          "0" "$(hasre '^[[:space:]]+device[[:space:]]+"hw:0,0"$' "$CONF")"
check "mixer_type hardware"    "0" "$(hasre '^[[:space:]]+mixer_type[[:space:]]+"hardware"$' "$CONF")"
check "mixer_device hw:0"      "0" "$(hasre '^[[:space:]]+mixer_device[[:space:]]+"hw:0"$' "$CONF")"
# "PCM" is the plausible-looking wrong answer; it does not exist on a pcm512x.
check "mixer_control Digital"  "0" "$(hasre '^[[:space:]]+mixer_control[[:space:]]+"Digital"$' "$CONF")"
check "mixer_control is NOT PCM" "1" "$(hasre '^[[:space:]]+mixer_control[[:space:]]+"PCM"$' "$CONF")"
check "exactly one audio_output block" "1" "$(count 'audio_output {' "$CONF")"
check "block is closed" "0" "$(hasre '^\}$' "$CONF")"

banner "settings that must not drift"
# inotify cannot see changes made on the far side of an NFS mount.
check "auto_update no"        "0" "$(hasre '^auto_update[[:space:]]+"no"$' "$CONF")"
check "auto_update not yes"   "1" "$(hasre '^auto_update[[:space:]]+"yes"$' "$CONF")"
check "the inotify reason is written down" "0" "$(has 'inotify' "$CONF")"
check "restore_paused yes"    "0" "$(hasre '^restore_paused[[:space:]]+"yes"$' "$CONF")"
check "runs as the mpd user"  "0" "$(hasre '^user[[:space:]]+"mpd"$' "$CONF")"
# Measured on the device: under socket activation MPD logs "No global port,
# disabling zeroconf", so declaring it would be a setting that silently lies.
check "no inert zeroconf_enabled" "1" "$(hasre '^zeroconf_enabled' "$CONF")"
check "and the reason is written down" "0" "$(has 'No global port' "$CONF")"
# mpd.socket passes listening sockets in; binding as well takes them away from
# systemd and needs a RuntimeDirectory drop-in to keep the unix socket.
check "no bind_to_address"    "1" "$(hasre '^bind_to_address' "$CONF")"

banner "state lives on persistent storage (setup.sh made /tmp and /var/log volatile)"
for f in db_file state_file sticker_file playlist_directory; do
    check "$f under /var/lib/mpd" "0" "$(hasre "^${f}[[:space:]]+\"/var/lib/mpd/" "$CONF")"
done
check "nothing under /tmp" "1" "$(has '"/tmp' "$CONF")"

banner "/etc/default/mpd — the MPDCONF mechanism"
check "MPDCONF points at our config" "0" "$(hasre '^MPDCONF=/etc/musicbox/mpd\.conf$' "$DEFAULTS")"
check "wrapped in the setup-mpd.sh marker" "0" \
    "$(grep -qx '# >>> musicbox setup-mpd.sh managed block >>>' "$DEFAULTS"; echo $?)"
check "closing marker on its own line" "0" \
    "$(grep -qx '# <<< musicbox setup-mpd.sh managed block <<<' "$DEFAULTS"; echo $?)"
check "marker never glued to the MPDCONF line" "1" "$(hasre '^MPDCONF=.*<<<' "$DEFAULTS")"
# CLAUDE.md rule 2: one marker per script, never shared.
for other in setup.sh setup-nas.sh setup-hardware.sh; do
    check "does not use ${other}'s marker" "1" "$(has ">>> musicbox ${other} managed block" "$DEFAULTS")"
done
check "stock content preserved above the block" "0" "$(has '# MPDCONF=/etc/mpd.conf' "$DEFAULTS")"

banner "it configures, it does not install (packages belong to install.sh)"
check "no apt-get in setup-mpd.sh" "1" "$(has 'apt-get install' "$SCRIPT")"
check "points at install.sh when mpd is missing" "0" "$(has 'run install.sh first' "$SCRIPT")"
check "install.sh installs mpd" "0" "$(hasre '^[[:space:]]+mpd[[:space:]]' "$REPO/install/install.sh")"
check "install.sh installs mpc" "0" "$(hasre '^[[:space:]]+mpc[[:space:]]' "$REPO/install/install.sh")"
check "/etc/mpd.conf is left alone" "1" "$(hasre '^[^#]*install .*[^x]/etc/mpd\.conf' "$SCRIPT")"

banner "re-running must not disturb a playing box"
# A blanket restart would stop playback mid-track on an idempotent re-run.
# Matching literal source text below, so the single quotes are deliberate.
# shellcheck disable=SC2016
check "restart is guarded by a change" "0" "$(hasre 'if \[\[ "\$changed" -eq 1 \]\]; then' "$SCRIPT")"
check "says why it does not restart" "0" "$(has 'it would interrupt playback' "$SCRIPT")"
check "still starts mpd if it is down" "0" "$(has 'systemctl start mpd.service' "$SCRIPT")"
# Copying on every run buries the pristine pre-musicbox file under modified copies.
check "backup only on the first run" "0" "$(has 'already carries our block' "$SCRIPT")"

banner "an absent library must warn, not fail"
# MPD is required to tolerate the share being down; dying here would contradict
# the whole point of the lazy automount.
check "unreadable library warns" "0" "$(has 'is not readable right now' "$SCRIPT")"
check "and does not die"         "1" "$(hasre 'die ".*'"$(printf '%s' '/srv/music/Music')"'.*not readable' "$SCRIPT")"

banner "managed block round-trip on a real fixture"
# Needs the internal functions, so source the script minus main.
HARNESS="$WORK/h.sh"
sed -e '$ d' -e 's/^readonly \(CONF_FILE\|DEFAULT_FILE\|CONF_DIR\|STATE_DIR\|MPD_STATE_DIR\|MUSIC_DIR\)=/\1=/' \
    "$SCRIPT" > "$HARNESS"
# shellcheck source=/dev/null
source "$HARNESS"
# The sourced script carries `set -euo pipefail`, which would now apply to THIS
# shell and abort the run on the first deliberately-failing assertion below.
set +e

FIX="$WORK/default-mpd"
cat > "$FIX" <<'FIXTURE'
## Defaults for the MPD init script, sourced by /etc/init.d/mpd on Debian
## systems.  Uncomment (remove the leading '#') and change values as needed.

## The configuration file location for mpd:
# MPDCONF=/etc/mpd.conf
FIXTURE
ORIG="$(cat "$FIX")"

# Exactly how do_apply calls it: command substitution strips the newline.
out="$(write_managed_block "$FIX" "$(gen_default_block)")"
cp "$out" "$FIX.new"; rm -f "$out"

check "one block after the first write" "1" "$(count '>>> musicbox setup-mpd.sh' "$FIX.new")"
check "MPDCONF line survives intact" "0" "$(hasre '^MPDCONF=/etc/musicbox/mpd\.conf$' "$FIX.new")"
check "the stock commented default is untouched" "0" "$(has '# MPDCONF=/etc/mpd.conf' "$FIX.new")"

out2="$(write_managed_block "$FIX.new" "$(gen_default_block)")"
check "re-writing leaves one block" "1" "$(count '>>> musicbox setup-mpd.sh' "$out2")"
check "re-writing is byte-identical" "0" "$(cmp -s "$FIX.new" "$out2"; echo $?)"
rm -f "$out2"

out3="$(strip_managed_block "$FIX.new")"
check "strip restores the original exactly" "$ORIG" "$(cat "$out3")"
rm -f "$out3"

banner "idempotency"
sum1="$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "re-emitting is byte-identical" "$sum1" "$(cat "$OUT"/* | md5sum)"

banner "usage/errors"
bash "$SCRIPT" --emit >/dev/null 2>&1
check "--emit without a destination fails" "1" "$?"
bash "$SCRIPT" --bogus >/dev/null 2>&1
check "unknown option fails" "1" "$?"
bash "$SCRIPT" --help >/dev/null 2>&1
check "--help exits 0" "0" "$?"
check "--help mentions --revert" "0" "$(bash "$SCRIPT" --help 2>/dev/null | grep -q -- '--revert'; echo $?)"

printf '\n===============================\n passed: %d   failed: %d\n===============================\n' "$PASS" "$FAIL"
[[ "$FAIL" -eq 0 ]]
