#!/usr/bin/env bash
#
# Tests the artifacts generated by install/setup-kiosk.sh via --emit, which
# touches no system state. Safe on a development machine.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO/install/setup-kiosk.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0; FAIL=0
check() {
    if [[ "$2" == "$3" ]]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$1"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s\n       expected: %q\n       actual:   %q\n' "$1" "$2" "$3"
    fi
}
banner() { printf '\n== %s ==\n' "$1"; }
has()    { grep -qF -- "$1" "$2"; echo $?; }
exists() { if [[ -e "$1" ]]; then echo 0; else echo 1; fi; }
count(){ grep -cF -- "$1" "$2"; }

OUT="$WORK/emit"
bash "$SCRIPT" --emit "$OUT" --hostname testbox >/dev/null 2>&1
check "emit exits 0" "0" "$?"

CONF="$OUT/kiosk.conf"; WRAP="$OUT/musicbox-kiosk"
UNIT="$OUT/musicbox-kiosk.service"; PAGE="$OUT/index.html"

banner "all four artifacts produced"
for f in "$CONF" "$WRAP" "$UNIT" "$PAGE"; do
    check "$(basename "$f") exists" "0" "$(exists "$f")"
done
check "wrapper is executable" "755" "$(stat -c %a "$WRAP")"

banner "wrapper is valid shell"
bash -n "$WRAP" 2>/dev/null
check "bash -n passes on the generated wrapper" "0" "$?"
check "wrapper has a shebang" "0" "$(head -1 "$WRAP" | grep -q '^#!' ; echo $?)"

banner "chromium flags"
for flag in --ozone-platform=wayland --kiosk --noerrdialogs --disable-infobars \
            --no-first-run --disable-session-crashed-bubble --password-store=basic \
            --autoplay-policy=no-user-gesture-required --overscroll-history-navigation=0 \
            --disable-pinch --mute-audio --disable-component-update \
            --touch-events=enabled; do
    check "$flag present" "0" "$(has "$flag" "$WRAP")"
done
check "--ozone-platform appears exactly once" "1" "$(count '--ozone-platform=wayland' "$WRAP")"
check "--kiosk appears exactly once"          "1" "$(count '--kiosk ' "$WRAP")"
check "profile dir pinned"  "0" "$(has '--user-data-dir=/var/lib/musicbox/chromium' "$WRAP")"
check "cage execs chromium" "0" "$(grep -qE '^exec cage -- ' "$WRAP"; echo $?)"
check "handles chromium-browser fallback" "0" "$(has 'chromium-browser' "$WRAP")"

banner "config drives the URL"
check "KIOSK_URL defined in conf" "0" "$(grep -qE '^KIOSK_URL=' "$CONF"; echo $?)"
check "default URL is the holding page" "0" "$(has 'file:///usr/share/musicbox/kiosk/index.html' "$CONF")"
check "wrapper sources the conf" "0" "$(has '/etc/musicbox/kiosk.conf' "$WRAP")"
# Deliberately unexpanded: we are matching the literal text in the wrapper.
# shellcheck disable=SC2016
check "wrapper uses the KIOSK_URL variable, not a literal" "0" "$(has '--kiosk "$KIOSK_URL"' "$WRAP")"
check "CHROMIUM_EXTRA_FLAGS honoured" "0" "$(has 'CHROMIUM_EXTRA_FLAGS' "$WRAP")"

# The conf must actually override the default when sourced. KIOSK_URL now points
# at the web server rather than the bundled holding page — see setup-server.sh.
# shellcheck source=/dev/null
( . "$CONF" >/dev/null 2>&1; [[ "$KIOSK_URL" == http://* ]] )
check "conf is sourceable and sets KIOSK_URL" "0" "$?"

# --url still selects the holding page, which is how you debug the panel itself
# without the app in the way.
bash "$SCRIPT" --emit "$WORK/holding" --url "file:///usr/share/musicbox/kiosk/index.html" \
    --hostname testbox >/dev/null 2>&1
# shellcheck source=/dev/null
( . "$WORK/holding/kiosk.conf" >/dev/null 2>&1; [[ "$KIOSK_URL" == file://* ]] )
check "--url can select the holding page" "0" "$?"
printf 'KIOSK_URL="http://localhost:8080/"\n' > "$WORK/override.conf"
# shellcheck source=/dev/null
( . "$WORK/override.conf"; [[ "$KIOSK_URL" == "http://localhost:8080/" ]] )
check "an override conf takes effect" "0" "$?"

banner "systemd unit — the lines that make or break the launch"
check "PAMName=login"                 "0" "$(grep -qx 'PAMName=login' "$UNIT"; echo $?)"
check "TTYPath=/dev/tty1"             "0" "$(grep -qx 'TTYPath=/dev/tty1' "$UNIT"; echo $?)"
check "Restart=always"                "0" "$(grep -qx 'Restart=always' "$UNIT"; echo $?)"
check "Conflicts=getty@tty1.service"  "0" "$(grep -qx 'Conflicts=getty@tty1.service' "$UNIT"; echo $?)"
check "runs as the kiosk user"        "0" "$(grep -qx 'User=musicbox' "$UNIT"; echo $?)"
check "WantedBy=multi-user.target"    "0" "$(grep -qx 'WantedBy=multi-user.target' "$UNIT"; echo $?)"
check "no graphical.target dependency" "1" "$(has 'graphical.target' "$UNIT")"
check "ExecStart points at the wrapper" "0" "$(grep -qx 'ExecStart=/usr/local/bin/musicbox-kiosk' "$UNIT"; echo $?)"
check "unit has all three sections" "3" "$(grep -cE '^\[(Unit|Service|Install)\]' "$UNIT")"

banner "--user changes the unit's User="
bash "$SCRIPT" --emit "$WORK/u2" --user pi --hostname testbox >/dev/null 2>&1
check "User=pi honoured" "0" "$(grep -qx 'User=pi' "$WORK/u2/musicbox-kiosk.service"; echo $?)"

banner "holding page"
check "hostname substituted"  "0" "$(has 'testbox.local' "$PAGE")"
check "has a title"           "0" "$(has '<title>musicbox</title>' "$PAGE")"
check "has a doctype"         "0" "$(head -1 "$PAGE" | grep -qi '<!doctype html>'; echo $?)"
check "cursor hidden for touch" "0" "$(has 'cursor: none' "$PAGE")"
check "has a touch diagnostic surface" "0" "$(has 'id="pad"' "$PAGE")"
check "counts touchstart"  "0" "$(has "addEventListener('touchstart'" "$PAGE")"
check "counts pointerdown" "0" "$(has "addEventListener('pointerdown'" "$PAGE")"
check "counts click"       "0" "$(has "addEventListener('click'" "$PAGE")"
check "reports tap coordinates" "0" "$(has 'id="xy"' "$PAGE")"
check "shows where the tap landed" "0" "$(has 'id="dot"' "$PAGE")"
check "touch-action none (no browser gesture capture)" "0" "$(has 'touch-action: none' "$PAGE")"
# `<head` also matches `<header`, hence the trailing space-or-bracket class.
check "tags balanced (html/head/body)" "0" "$(for t in html head body; do
        o=$(grep -coE "<${t}[[:space:]>]" "$PAGE"); c=$(grep -coE "</${t}>" "$PAGE");
        [ "$o" -eq 1 ] && [ "$c" -eq 1 ] || exit 1; done; echo $?)"
check "points at the conf file for the real URL" "0" "$(has '/etc/musicbox/kiosk.conf' "$PAGE")"

banner "idempotency"
sum1="$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit "$OUT" --hostname testbox >/dev/null 2>&1
check "re-emitting is byte-identical" "$sum1" "$(cat "$OUT"/* | md5sum)"

banner "usage/errors"
bash "$SCRIPT" --emit >/dev/null 2>&1
check "--emit without a destination fails" "1" "$?"
bash "$SCRIPT" --bogus >/dev/null 2>&1
check "unknown option fails" "1" "$?"
bash "$SCRIPT" --help >/dev/null 2>&1
check "--help exits 0" "0" "$?"

printf '\n===============================\n passed: %d   failed: %d\n===============================\n' "$PASS" "$FAIL"
[[ "$FAIL" -eq 0 ]]
