#!/usr/bin/env bash
#
# Tests the units and config generated by install/setup-server.sh via --emit,
# which needs no root and touches no system state. Safe on a development machine.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO/install/setup-server.sh"
KIOSK="$REPO/install/setup-kiosk.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0; FAIL=0
check() {
    if [[ "$2" == "$3" ]]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$1"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s\n       expected: %q\n       actual:   %q\n' "$1" "$2" "$3"
    fi
}
banner() { printf '\n== %s ==\n' "$1"; }
has()    { grep -qF -- "$1" "$2"; echo $?; }
hasre()  { grep -qE -- "$1" "$2"; echo $?; }
count()  { grep -cF -- "$1" "$2"; }

OUT="$WORK/emit"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "emit exits 0" "0" "$?"

CONF="$OUT/server.conf"
UNIT="$OUT/musicbox-server.service"
RESTART="$OUT/musicbox-server-restart.service"
PATHU="$OUT/musicbox-server.path"
for f in "$CONF" "$UNIT" "$RESTART" "$PATHU"; do
    check "$(basename "$f") written" "0" "$(if [[ -f "$f" ]]; then echo 0; else echo 1; fi)"
done

banner "THE BOOT CONTRACT — the server must not sit behind mpd"
# mpd.service takes ~6s and is on the critical path. Ordering the web server
# after it would add that delay for no benefit. This is THE regression to catch.
check "no After=mpd"            "1" "$(hasre '^After=.*mpd' "$UNIT")"
check "no Requires=mpd"         "1" "$(hasre '^(Requires|BindsTo|Wants)=.*mpd\.service' "$UNIT")"
# network.target is not reached until NetworkManager starts (~6s here), and
# binding 0.0.0.0 does not need an interface up first.
check "no After=network.target" "1" "$(hasre '^After=network\.target' "$UNIT")"
check "the reason is written down" "0" "$(has 'LOAD-BEARING' "$UNIT")"
check "starts at multi-user"    "0" "$(hasre '^WantedBy=multi-user\.target$' "$UNIT")"

banner "port 80 without root"
check "ambient capability granted" "0" "$(hasre '^AmbientCapabilities=CAP_NET_BIND_SERVICE$' "$UNIT")"
check "bounding set is narrowed"   "0" "$(hasre '^CapabilityBoundingSet=CAP_NET_BIND_SERVICE$' "$UNIT")"
check "no new privileges"          "0" "$(hasre '^NoNewPrivileges=yes$' "$UNIT")"
check "does NOT run as root"       "1" "$(hasre '^User=root$' "$UNIT")"
check "runs as musicbox"           "0" "$(hasre '^User=musicbox$' "$UNIT")"
# /home/musicbox is 0700, so ProtectHome would make the deploy dir unreadable.
check "ProtectHome is not set"     "1" "$(hasre '^ProtectHome=' "$UNIT")"
check "and that is explained"      "0" "$(has 'ProtectHome is NOT set' "$UNIT")"

banner "service basics"
check "restarts on failure" "0" "$(hasre '^Restart=on-failure$' "$UNIT")"
check "runs the bundle"     "0" "$(hasre '^ExecStart=/usr/bin/node .*/backend/server\.js$' "$UNIT")"
check "no npm on the device" "1" "$(has 'npm' "$UNIT")"
# /api/events never finishes on its own; when that wedged Fastify's close() the
# service sat in 'deactivating' for systemd's default 90s.
check "shutdown is time-bounded" "0" "$(hasre '^TimeoutStopSec=[0-9]+$' "$UNIT")"

banner "a deploy restarts the service with no sudo"
check "path unit watches the bundle" "0" "$(hasre '^PathChanged=.*/backend/server\.js$' "$PATHU")"
check "path unit triggers the restart shim" "0" \
    "$(hasre '^Unit=musicbox-server-restart\.service$' "$PATHU")"
check "shim actually restarts"  "0" "$(hasre '^ExecStart=.*systemctl restart musicbox-server\.service$' "$RESTART")"
check "shim is a oneshot"       "0" "$(hasre '^Type=oneshot$' "$RESTART")"
check "path unit is enabled at boot" "0" "$(hasre '^WantedBy=multi-user\.target$' "$PATHU")"
# A .path can only START a unit; restarting a running service needs the shim.
check "why the shim exists is written down" "0" "$(has 'can only START a unit' "$RESTART")"

banner "config drives the server, not the unit"
check "port in conf"       "0" "$(hasre '^MUSICBOX_PORT=80$' "$CONF")"
check "mpd host in conf"   "0" "$(hasre '^MUSICBOX_MPD_HOST=127\.0\.0\.1$' "$CONF")"
check "mpd port in conf"   "0" "$(hasre '^MUSICBOX_MPD_PORT=6600$' "$CONF")"
check "web root in conf"   "0" "$(hasre '^MUSICBOX_WEB_ROOT=.*/frontend$' "$CONF")"
check "unit hardcodes no port" "1" "$(hasre '^Environment=MUSICBOX_PORT' "$UNIT")"

banner "flags change the generated output"
bash "$SCRIPT" --emit "$WORK/alt" --port 8080 --mpd-host nas.local --user pi \
    --deploy-dir /opt/mb >/dev/null 2>&1
check "--port honoured"       "0" "$(hasre '^MUSICBOX_PORT=8080$' "$WORK/alt/server.conf")"
check "--mpd-host honoured"   "0" "$(hasre '^MUSICBOX_MPD_HOST=nas\.local$' "$WORK/alt/server.conf")"
check "--user honoured"       "0" "$(hasre '^User=pi$' "$WORK/alt/musicbox-server.service")"
check "--deploy-dir honoured" "0" "$(hasre '^ExecStart=/usr/bin/node /opt/mb/backend/server\.js$' "$WORK/alt/musicbox-server.service")"
check "path unit follows deploy-dir" "0" "$(hasre '^PathChanged=/opt/mb/backend/server\.js$' "$WORK/alt/musicbox-server.path")"

banner "the kiosk waits for the server and points at it"
KOUT="$WORK/kiosk"
bash "$KIOSK" --emit "$KOUT" --hostname testbox >/dev/null 2>&1
check "kiosk emit exits 0" "0" "$?"
check "kiosk ordered after the server" "0" \
    "$(hasre '^After=musicbox-server\.service$' "$KOUT/musicbox-kiosk.service")"
# Wants, not Requires: a broken server should still leave a panel that says so.
check "kiosk Wants (not Requires) the server" "0" \
    "$(hasre '^Wants=musicbox-server\.service$' "$KOUT/musicbox-kiosk.service")"
check "kiosk does not hard-require it" "1" \
    "$(hasre '^Requires=musicbox-server\.service$' "$KOUT/musicbox-kiosk.service")"
check "KIOSK_URL points at the web UI" "0" \
    "$(hasre '^KIOSK_URL="http://localhost/"$' "$KOUT/kiosk.conf")"
check "no longer the holding page" "1" "$(hasre '^KIOSK_URL="file://' "$KOUT/kiosk.conf")"
check "wrapper default matches" "0" "$(has 'KIOSK_URL:-http://localhost/' "$KOUT/musicbox-kiosk")"
check "MPD still owns the DAC" "0" "$(has '--mute-audio' "$KOUT/musicbox-kiosk")"

banner "it configures, it does not install"
check "no apt-get in setup-server.sh" "1" "$(has 'apt-get install' "$SCRIPT")"
check "points at install.sh when node is missing" "0" "$(has 'run install.sh first' "$SCRIPT")"
check "install.sh installs nodejs" "0" "$(hasre '^[[:space:]]+nodejs[[:space:]]' "$REPO/install/install.sh")"
check "install.sh does NOT install npm" "1" "$(hasre '^[[:space:]]+npm[[:space:]]' "$REPO/install/install.sh")"
check "the npm package-count reason is recorded" "0" "$(has '363' "$REPO/install/install.sh")"

banner "idempotency and CLI"
sum1="$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "re-emitting is byte-identical" "$sum1" "$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit >/dev/null 2>&1
check "--emit without a destination fails" "1" "$?"
bash "$SCRIPT" --bogus >/dev/null 2>&1
check "unknown option fails" "1" "$?"
bash "$SCRIPT" --help >/dev/null 2>&1
check "--help exits 0" "0" "$?"
check "--help mentions --revert" "0" "$(bash "$SCRIPT" --help 2>/dev/null | grep -q -- '--revert'; echo $?)"

banner "the dev loop exists and needs no sudo"
check "dev-push.sh present"   "0" "$(if [[ -x "$REPO/tools/dev-push.sh" ]]; then echo 0; else echo 1; fi)"
check "build.sh present"      "0" "$(if [[ -x "$REPO/tools/build.sh" ]]; then echo 0; else echo 1; fi)"
check "dev-push uses rsync"   "0" "$(has 'rsync -a' "$REPO/tools/dev-push.sh")"
# --inplace would overwrite the watched file in place and break the .path
# trigger. The string appears in a comment explaining that, so check the actual
# rsync invocations rather than the whole file.
check "no rsync invocation uses --inplace" "1" \
    "$(grep -E '^[[:space:]]*rsync ' "$REPO/tools/dev-push.sh" | grep -q -- '--inplace'; echo $?)"
# "sudo" appears in a comment and in an apt hint; what must not exist is an
# actual sudo invocation, which would put a password prompt in the inner loop.
check "sudo is never invoked" "1" \
    "$(grep -qE '^[[:space:]]*sudo ' "$REPO/tools/dev-push.sh"; echo $?)"
check "dev-push never builds on the device" "1" "$(has 'ssh.*npm' "$REPO/tools/dev-push.sh")"

banner "album art: the music root must agree with MPD's music_directory"
# If these two drift, EVERY art request 404s and nothing else misbehaves — a
# miserable thing to debug from the symptom. So compare the literals directly.
# MUSIC_DIR is built from MOUNT_POINT, so resolve the reference rather than
# comparing the literal.
MPD_MOUNT_POINT="$(grep -oE '^readonly MOUNT_POINT="[^"]*"' "$REPO/install/setup-mpd.sh" | head -1 | sed 's/.*="//; s/"$//')"
MPD_MUSIC_DIR="$(grep -oE '^readonly MUSIC_DIR="[^"]*"' "$REPO/install/setup-mpd.sh" | head -1 | sed 's/.*="//; s/"$//')"
MPD_MUSIC_DIR="${MPD_MUSIC_DIR//\$\{MOUNT_POINT\}/$MPD_MOUNT_POINT}"
BACKEND_MUSIC_ROOT="$(grep -oE "musicRoot: '[^']*'" "$REPO/src/backend/src/config.ts" | head -1 | sed "s/.*: '//; s/'$//")"
check "setup-mpd.sh MOUNT_POINT was found"      "0" "$(if [[ -n "$MPD_MOUNT_POINT" ]]; then echo 0; else echo 1; fi)"
check "setup-mpd.sh MUSIC_DIR was found"        "0" "$(if [[ -n "$MPD_MUSIC_DIR" ]]; then echo 0; else echo 1; fi)"
# shellcheck disable=SC2016
check "MUSIC_DIR resolved, not left literal"    "1" "$(printf '%s' "$MPD_MUSIC_DIR" | grep -qF '${'; echo $?)"
check "backend musicRoot default was found"     "0" "$(if [[ -n "$BACKEND_MUSIC_ROOT" ]]; then echo 0; else echo 1; fi)"
check "the two paths are identical"             "$MPD_MUSIC_DIR" "$BACKEND_MUSIC_ROOT"

banner "album art: the endpoint and its guards"
ART="$REPO/src/backend/src/art.ts"
check "art.ts exists"                    "0" "$(if [[ -f "$ART" ]]; then echo 0; else echo 1; fi)"
check "reuses safeJoin for traversal"     "0" "$(has 'safeJoin' "$ART")"
check "folder.jpg is a candidate"         "0" "$(has "'folder.jpg'" "$ART")"
check "cover.jpg is a candidate"          "0" "$(has "'cover.jpg'" "$ART")"
# The trap: discart outnumbers cover 44:1 in this library and is a round disc
# image. It is named in the comments explaining the exclusion, so assert it is
# never a QUOTED candidate string rather than merely absent from the file.
check "discart is NEVER a candidate"      "1" "$(grep -qE "^\s+'discart\." "$ART"; echo $?)"
check "fanart is NEVER a candidate"       "1" "$(grep -qE "^\s+'fanart\." "$ART"; echo $?)"
check "clearlogo is NEVER a candidate"    "1" "$(grep -qE "^\s+'clearlogo\." "$ART"; echo $?)"
check "Synology @eaDir is excluded"       "0" "$(has '@eaDir' "$ART")"
check "the route is registered"           "0" "$(has "/api/art" "$REPO/src/backend/src/routes.ts")"
check "Track carries image"               "0" "$(has 'image: string' "$REPO/src/shared/api.ts")"
# No transition on the art element: repaints on this panel are the vc4 commit
# path implicated in the clock deadlock.
check "no CSS transition on the art"      "1" \
    "$(awk '/^\.art \{/,/^\}/' "$REPO/src/frontend/src/app/app.scss" | grep -qE 'transition|animation'; echo $?)"

banner "a frontend deploy must actually reach the kiosk"
# The bug this guards: the panel loads the page once at boot and has no keyboard,
# so a frontend deploy left it running a 14-hour-old bundle while the correct
# files sat on disk being served. The chain is: index.html changes -> the .path
# unit restarts the service -> SSE streams drop -> clients re-read the build id
# and reload. Every link is asserted.
EMIT_DIR="$(mktemp -d)"
bash "$SCRIPT" --emit "$EMIT_DIR" >/dev/null 2>&1
PATH_UNIT_FILE="$EMIT_DIR/musicbox-server.path"
check "the path unit was emitted"              "0" "$(if [[ -f "$PATH_UNIT_FILE" ]]; then echo 0; else echo 1; fi)"
# Must be actual directives, not the comment that explains them.
check "it watches the backend bundle"          "0" \
    "$(grep -qE '^PathChanged=.*/backend/server\.js$' "$PATH_UNIT_FILE"; echo $?)"
check "it watches frontend/index.html"         "0" \
    "$(grep -qE '^PathChanged=.*/frontend/index\.html$' "$PATH_UNIT_FILE"; echo $?)"
check "exactly two watched paths"              "2" \
    "$(grep -cE '^PathChanged=' "$PATH_UNIT_FILE")"
rm -rf "$EMIT_DIR"

check "the server announces its build over SSE" "0" \
    "$(has 'SSE_BUILD_EVENT' "$REPO/src/backend/src/routes.ts")"
check "the client reloads on a build change"    "0" \
    "$(has 'location.reload()' "$REPO/src/frontend/src/app/services/musicbox-api.ts")"
# dev-push used to tell the user to "just reload the page", which is impossible
# on a panel with no keyboard. It must not say that again.
check "dev-push does not tell you to reload by hand" "1" \
    "$(grep -qE 'just reload the page.$' "$REPO/tools/dev-push.sh"; echo $?)"
check "dev-push waits for health on every scope"  "1" \
    "$(grep -qE 'SCOPE.*==.*frontend.*\]\]; then' "$REPO/tools/dev-push.sh"; echo $?)"

banner "every API url goes through the configured origin"
# environment.apiUrl lets a dev frontend talk to the real box. Anything that
# bypasses the resolver is fetched from the PAGE's origin instead — which for
# Track.image (a root-relative path the SERVER sends) meant art 404ing in that
# setup. The <img> binding must resolve it like every other API call.
API_TS="$REPO/src/frontend/src/app/services/musicbox-api.ts"
# Transport moved out of musicbox-api.ts when library browse landed: two
# services now need it (playback state and the browse catalogue) and neither
# should own it. resolve() lives here; musicbox-api.ts keeps a delegating
# resolve() because every caller and the Angular spec name it there.
CLIENT_TS="$REPO/src/frontend/src/app/services/api-client.ts"
STORE_TS="$REPO/src/frontend/src/app/services/library-store.ts"
# The UI, not app.ts: this used to look in app.ts, which stopped holding any of
# it when now-playing was extracted — so the check silently passed against a file
# that could never contain a violation. There is more than one art binding now
# (now-playing and the queue), so it is asked of both UI directories.
UI=("$REPO/src/frontend/src/app/components" "$REPO/src/frontend/src/app/routes")
check "the resolver exists and is public"   "0" "$(grep -qE '^\s+resolve\(path: string\)' "$CLIENT_TS"; echo $?)"
# It stays reachable under its old name too. Components call api.resolve() for
# art, and moving it without leaving this behind would break every one silently.
check "musicbox-api still exposes resolve"  "0" "$(grep -qE '^\s+resolve\(path: string\)' "$API_TS"; echo $?)"
# The client is the only thing allowed to call fetch, and every call it makes
# must be resolved. This is the assertion the per-service ones below lean on.
check "every fetch in the client is resolved" \
    "$(grep -c 'fetch(' "$CLIENT_TS")" \
    "$(grep -c 'fetch(this.resolve(' "$CLIENT_TS")"
check "no fetch outside the client"         "1" \
    "$(grep -rqE '\bfetch\(' "$API_TS" "$STORE_TS" "${UI[@]}"; echo $?)"
check "no private url() helper remains"     "1" "$(grep -q 'this\.url(' "$API_TS"; echo $?)"
check "the art is resolved, not bound raw"  "0" \
    "$(grep -rq 'api\.resolve(' "${UI[@]}"; echo $?)"
# The raw field must never reach a template directly — that is the bug this
# whole block exists for.
check "no template binds .image"            "1" \
    "$(grep -rq '\.image' "${UI[@]}" --include='*.html'; echo $?)"
# A Bluetooth source answers 409 to GET /api/queue. The snapshot already said so
# with queueVersion -1, so the client must not ask.
check "the queue is not fetched without a version" "0" \
    "$(has 'queueVersion() < 0' "$API_TS")"
# Every literal /api path in either service must reach the network through the
# client — resolve() directly, or getJson()/post(), which resolve internally.
#
# Comments are stripped first: the doc comments mention /api/art, and matching
# THAT would be asserting against the explanation rather than a violation — a
# mistake this repo has already paid for once (see decisions.md).
#
# The file is then collapsed to ONE LINE before matching, which is the part that
# matters. A line-by-line version passed for a year and then broke the moment
# calls grew a type parameter (`getJson<QueueResponse>(`) or wrapped across two
# lines, because the path and its callee stopped sharing a line.
#
# What is matched is the CALLEE IMMEDIATELY BEFORE the literal, not a window of
# preceding text. A window was tried first and silently passed the mutation
# below: the literal happened to sit near the word `resolve` in an unrelated
# method, so a bare fetch() looked wrapped.
#
# Type parameters are deleted before matching. Without that, `getJson<T>(` reads
# as an identifier followed by a `<...>` that the regex will happily stretch back
# across the collapsed line to an earlier `Promise<T>`, and the callee that comes
# out is `Promise`.
unwrapped_api() {
    sed -E 's://.*$::' "$1" \
        | grep -vE '^[[:space:]]*(\*|/\*)' \
        | tr '\n' ' ' \
        | sed -E 's/<[^<>()]*>//g' \
        | grep -oE "[A-Za-z0-9_]+\\([[:space:]]*[\`'\"]/api/" \
        | grep -vcE "^(resolve|getJson|post)" || true
}
# Asserted per file rather than over the directory so a new service cannot be
# added and quietly skipped.
for svc in "$API_TS" "$STORE_TS"; do
    check "no unwrapped /api literal in $(basename "$svc")" "0" "$(unwrapped_api "$svc")"
done
# The guard must be able to fail. A literal with no resolver in front of it is
# the exact bug, and a check that cannot go red is not a check — this repo has
# shipped one of those before (see the COMPONENTS note above).
MUTANT="$WORK/mutant.ts"
{ cat "$STORE_TS"; printf "\nconst leak = await fetch('/api/library/artists');\n"; } > "$MUTANT"
check "the guard catches an unresolved literal" "1" "$(unwrapped_api "$MUTANT")"

printf '\n===============================\n passed: %d   failed: %d\n===============================\n' "$PASS" "$FAIL"
[[ "$FAIL" -eq 0 ]]
