#!/usr/bin/env bash
#
# Tests the artifacts generated by install/setup-cd.sh via --emit, and drives the
# generated helper with stubbed udevadm/mpc/eject. No root, no system state.
#
# SC2016: assertions grep generated text for literal "$VAR" strings.
# shellcheck disable=SC2016
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO/install/setup-cd.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0; FAIL=0
check() {
    if [[ "$2" == "$3" ]]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$1"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s\n       expected: %q\n       actual:   %q\n' "$1" "$2" "$3"
    fi
}
banner() { printf '\n== %s ==\n' "$1"; }
has()    { grep -qF -- "$1" "$2"; echo $?; }
hasre()  { grep -qE -- "$1" "$2"; echo $?; }

OUT="$WORK/emit"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "emit exits 0" "0" "$?"

HELPER="$OUT/musicbox-cd"
UNIT="$OUT/musicbox-cd.service"
for f in "$HELPER" "$UNIT"; do
    check "$(basename "$f") written" "0" "$(if [[ -f "$f" ]]; then echo 0; else echo 1; fi)"
done
check "helper is executable" "0" "$(if [[ -x "$HELPER" ]]; then echo 0; else echo 1; fi)"
check "helper parses" "0" "$(bash -n "$HELPER"; echo $?)"

banner "the unit"
check "runs the monitor" "0" "$(has 'ExecStart=/usr/local/bin/musicbox-cd monitor' "$UNIT")"
check "not root" "0" "$(hasre '^User=musicbox$' "$UNIT")"
check "in cdrom, to eject" "0" "$(hasre '^SupplementaryGroups=cdrom$' "$UNIT")"
check "its own runtime directory" "0" "$(hasre '^RuntimeDirectory=musicbox-cd$' "$UNIT")"
# /run/musicbox is musicbox-bt-monitor's; two owners is the dead-inode trap.
check "never /run/musicbox itself" "1" "$(hasre '^RuntimeDirectory=musicbox$' "$UNIT")"
check "the directory survives a restart" "0" "$(has 'RuntimeDirectoryPreserve=yes' "$UNIT")"
check "restarts if it dies" "0" "$(has 'Restart=always' "$UNIT")"
check "not ordered after the web server" "1" "$(hasre '^(After|Wants|Requires)=.*musicbox-server' "$UNIT")"

banner "the paths agree with the backend"
CD_TS="$REPO/src/backend/src/cd.ts"
state_path="$(sed -n 's/^STATE_FILE="\(.*\)"$/\1/p' "$HELPER")"
fifo_path="$(sed -n 's/^CONTROL_FIFO="\(.*\)"$/\1/p' "$HELPER")"
check "state file matches DEFAULT_CD_STATE_PATH" "0" "$(has "DEFAULT_CD_STATE_PATH = '${state_path}'" "$CD_TS")"
check "control FIFO matches DEFAULT_CD_CONTROL_PATH" "0" "$(has "DEFAULT_CD_CONTROL_PATH = '${fifo_path}'" "$CD_TS")"
verbs_ts="$(sed -n "s/^export const CD_CONTROL_VERBS = \[\(.*\)\] as const;$/\1/p" "$CD_TS" | tr -d " '" | tr ',' '\n' | sort)"
verbs_sh="$(sed -n '/^handle_ctl()/,/^}/p' "$HELPER" | sed -n 's/^[[:space:]]*\([a-z]*\))[[:space:]].*/\1/p' | sort)"
check "control verbs agree with CD_CONTROL_VERBS" "$verbs_ts" "$verbs_sh"

banner "driving the helper"
BIN="$WORK/bin"; mkdir -p "$BIN"
export STUB_CALLS="$WORK/calls"; : > "$STUB_CALLS"
export STUB_TRACKS="$WORK/tracks"
export STUB_CURRENT="$WORK/current"; : > "$STUB_CURRENT"
cat > "$BIN/udevadm" <<'STUB'
#!/usr/bin/env bash
printf 'udevadm %s\n' "$*" >> "$STUB_CALLS"
printf 'ID_CDROM=1\n'
[[ -s "$STUB_TRACKS" ]] && printf 'ID_CDROM_MEDIA=1\nID_CDROM_MEDIA_TRACK_COUNT_AUDIO=%s\n' "$(cat "$STUB_TRACKS")"
exit 0
STUB
cat > "$BIN/mpc" <<'STUB'
#!/usr/bin/env bash
printf 'mpc %s\n' "$*" >> "$STUB_CALLS"
[[ "$1" == current ]] && cat "$STUB_CURRENT"
exit 0
STUB
cat > "$BIN/eject" <<'STUB'
#!/usr/bin/env bash
printf 'eject %s\n' "$*" >> "$STUB_CALLS"
: > "$STUB_TRACKS"
exit 0
STUB
chmod +x "$BIN"/*

DRIVEDIR="$WORK/drive"; mkdir -p "$DRIVEDIR"
sed -e '$ d' "$HELPER" > "$DRIVEDIR/lib.sh"
export CD_LIB="$DRIVEDIR/lib.sh" CD_STATE="$DRIVEDIR/cd.json" CD_LOG="$DRIVEDIR/log"
cat > "$DRIVEDIR/drive.sh" <<'DRIVE'
#!/usr/bin/env bash
# shellcheck source=/dev/null
source "$CD_LIB"
STATE_FILE="$CD_STATE"
RUN_DIR="$(dirname "$CD_STATE")"
# Each argument is "udev LINE", "ctl VERB", or "tracks N" to change the disc.
for step in "$@"; do
    kind="${step%% *}"; rest="${step#* }"
    case "$kind" in
        tracks) if [[ "$rest" == 0 ]]; then : > "$STUB_TRACKS"; else printf '%s' "$rest" > "$STUB_TRACKS"; fi; continue ;;
        udev)   handle_udev "$rest" >> "$CD_LOG" 2>&1 ;;
        ctl)    handle_ctl  "$rest" >> "$CD_LOG" 2>&1 ;;
    esac
    cat "$STATE_FILE" 2>/dev/null || echo none
done
DRIVE

drive() { PATH="$BIN:$PATH" bash "$DRIVEDIR/drive.sh" "$@"; }

: > "$STUB_TRACKS"
mapfile -t S < <(drive "udev DEVNAME=/dev/sr0" "tracks 11" "udev DEVNAME=/dev/sr0" "udev ACTION=change")
check "an empty drive publishes present:false" '{"present":false}' "${S[0]:-}"
check "an audio disc publishes its track count" '{"present":true,"tracks":11}' "${S[1]:-}"
check "unrelated property lines change nothing" '{"present":true,"tracks":11}' "${S[2]:-}"

rm -f "$CD_STATE"; : > "$STUB_TRACKS"
mapfile -t S < <(drive "tracks 0" "udev DEVNAME=/dev/sr0")
check "a data disc (no audio tracks) is not a CD" '{"present":false}' "${S[0]:-}"

# Eject from the UI while MPD plays the disc: stop first, then eject.
rm -f "$CD_STATE"; : > "$STUB_CALLS"; printf '5' > "$STUB_TRACKS"
printf 'cdda:///3\n' > "$STUB_CURRENT"
mapfile -t S < <(drive "udev DEVNAME=/dev/sr0" "ctl eject")
check "ctl eject publishes present:false" '{"present":false}' "${S[1]:-}"
stop_at="$(grep -n '^mpc -q stop' "$STUB_CALLS" | head -1 | cut -d: -f1)"
eject_at="$(grep -n '^eject ' "$STUB_CALLS" | head -1 | cut -d: -f1)"
check "MPD is stopped before the tray opens" "0" \
    "$(if [[ -n "$stop_at" && -n "$eject_at" && "$stop_at" -lt "$eject_at" ]]; then echo 0; else echo 1; fi)"
check "eject names the drive" "0" "$(grep -qx 'eject /dev/cdrom' "$STUB_CALLS"; echo $?)"

# Library track playing: eject must not stop it.
: > "$STUB_CALLS"; printf '5' > "$STUB_TRACKS"
printf 'Artist/Album/01.flac\n' > "$STUB_CURRENT"
drive "ctl eject" >/dev/null
check "a library track is not stopped by an eject" "1" "$(grep -q '^mpc -q stop' "$STUB_CALLS"; echo $?)"

# The physical button: udev's own rule ejects, so we only stop MPD.
: > "$STUB_CALLS"; printf 'cdda:///1\n' > "$STUB_CURRENT"
drive "udev DISK_EJECT_REQUEST=1" >/dev/null
check "the eject button stops MPD on the disc" "0" "$(grep -q '^mpc -q stop' "$STUB_CALLS"; echo $?)"
check "and leaves the eject to udev" "1" "$(grep -q '^eject ' "$STUB_CALLS"; echo $?)"

: > "$STUB_CALLS"
drive "ctl reboot" >/dev/null
check "an unknown verb runs nothing" "" "$(grep -v '^udevadm\|^mpc current' "$STUB_CALLS")"

# A restart must read as "unknown", never as "no disc" — see the trap.
check "exit removes the state file rather than publishing none" "0" \
    "$(grep -q "trap \"rm -f '\$fifo' '\$CONTROL_FIFO' '\$STATE_FILE'\" EXIT" "$HELPER"; echo $?)"

banner "it configures, it does not install"
check "no apt-get in setup-cd.sh" "1" "$(hasre '^[[:space:]]*(run )?(env .*)?apt-get ' "$SCRIPT")"
check "install.sh installs eject" "0" "$(hasre '^[[:space:]]+eject([[:space:]]|$)' "$REPO/install/install.sh")"
check "MPD joins cdrom" "0" "$(has 'usermod -aG "$CD_GROUP" "$MPD_USER"' "$SCRIPT")"
check "revert takes it out again" "0" "$(has 'gpasswd -d "$MPD_USER" "$CD_GROUP"' "$SCRIPT")"

banner "idempotency and CLI"
check "--emit must be silent" "" "$(bash "$SCRIPT" --emit "$WORK/silent" 2>&1 >/dev/null)"
sum1="$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "re-emitting is byte-identical" "$sum1" "$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit >/dev/null 2>&1
check "--emit without a destination fails" "1" "$?"
bash "$SCRIPT" --bogus >/dev/null 2>&1
check "unknown option fails" "1" "$?"
check "--help mentions --revert" "0" "$(bash "$SCRIPT" --help 2>/dev/null | grep -q -- '--revert'; echo $?)"
check "--help mentions --dry-run" "0" "$(bash "$SCRIPT" --help 2>/dev/null | grep -q -- '--dry-run'; echo $?)"
check "--revert without root fails" "1" "$(bash "$SCRIPT" --revert >/dev/null 2>&1; echo $?)"
check "apply without root fails" "1" "$(bash "$SCRIPT" >/dev/null 2>&1; echo $?)"

printf '\n===============================\n passed: %d   failed: %d\n===============================\n' "$PASS" "$FAIL"
[[ "$FAIL" -eq 0 ]]
