#!/usr/bin/env bash
#
# Tests the units and config generated by install/setup-server.sh via --emit,
# which needs no root and touches no system state. Safe on a development machine.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO/install/setup-server.sh"
KIOSK="$REPO/install/setup-kiosk.sh"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

PASS=0; FAIL=0
check() {
    if [[ "$2" == "$3" ]]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$1"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s\n       expected: %q\n       actual:   %q\n' "$1" "$2" "$3"
    fi
}
banner() { printf '\n== %s ==\n' "$1"; }
has()    { grep -qF -- "$1" "$2"; echo $?; }
hasre()  { grep -qE -- "$1" "$2"; echo $?; }
count()  { grep -cF -- "$1" "$2"; }

OUT="$WORK/emit"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "emit exits 0" "0" "$?"

CONF="$OUT/server.conf"
UNIT="$OUT/musicbox-server.service"
RESTART="$OUT/musicbox-server-restart.service"
PATHU="$OUT/musicbox-server.path"
for f in "$CONF" "$UNIT" "$RESTART" "$PATHU"; do
    check "$(basename "$f") written" "0" "$(if [[ -f "$f" ]]; then echo 0; else echo 1; fi)"
done

banner "THE BOOT CONTRACT — the server must not sit behind mpd"
# mpd.service takes ~6s and is on the critical path. Ordering the web server
# after it would add that delay for no benefit. This is THE regression to catch.
check "no After=mpd"            "1" "$(hasre '^After=.*mpd' "$UNIT")"
check "no Requires=mpd"         "1" "$(hasre '^(Requires|BindsTo|Wants)=.*mpd\.service' "$UNIT")"
# network.target is not reached until NetworkManager starts (~6s here), and
# binding 0.0.0.0 does not need an interface up first.
check "no After=network.target" "1" "$(hasre '^After=network\.target' "$UNIT")"
check "the reason is written down" "0" "$(has 'LOAD-BEARING' "$UNIT")"
check "starts at multi-user"    "0" "$(hasre '^WantedBy=multi-user\.target$' "$UNIT")"

banner "port 80 without root"
check "ambient capability granted" "0" "$(hasre '^AmbientCapabilities=CAP_NET_BIND_SERVICE$' "$UNIT")"
check "bounding set is narrowed"   "0" "$(hasre '^CapabilityBoundingSet=CAP_NET_BIND_SERVICE$' "$UNIT")"
check "no new privileges"          "0" "$(hasre '^NoNewPrivileges=yes$' "$UNIT")"
check "does NOT run as root"       "1" "$(hasre '^User=root$' "$UNIT")"
check "runs as musicbox"           "0" "$(hasre '^User=musicbox$' "$UNIT")"
# /home/musicbox is 0700, so ProtectHome would make the deploy dir unreadable.
check "ProtectHome is not set"     "1" "$(hasre '^ProtectHome=' "$UNIT")"
check "and that is explained"      "0" "$(has 'ProtectHome is NOT set' "$UNIT")"

banner "service basics"
check "restarts on failure" "0" "$(hasre '^Restart=on-failure$' "$UNIT")"
check "runs the bundle"     "0" "$(hasre '^ExecStart=/usr/bin/node .*/backend/server\.js$' "$UNIT")"
check "no npm on the device" "1" "$(has 'npm' "$UNIT")"
# /api/events never finishes on its own; when that wedged Fastify's close() the
# service sat in 'deactivating' for systemd's default 90s.
check "shutdown is time-bounded" "0" "$(hasre '^TimeoutStopSec=[0-9]+$' "$UNIT")"

banner "a deploy restarts the service with no sudo"
check "path unit watches the bundle" "0" "$(hasre '^PathChanged=.*/backend/server\.js$' "$PATHU")"
check "path unit triggers the restart shim" "0" \
    "$(hasre '^Unit=musicbox-server-restart\.service$' "$PATHU")"
check "shim actually restarts"  "0" "$(hasre '^ExecStart=.*systemctl restart musicbox-server\.service$' "$RESTART")"
check "shim is a oneshot"       "0" "$(hasre '^Type=oneshot$' "$RESTART")"
check "path unit is enabled at boot" "0" "$(hasre '^WantedBy=multi-user\.target$' "$PATHU")"
# A .path can only START a unit; restarting a running service needs the shim.
check "why the shim exists is written down" "0" "$(has 'can only START a unit' "$RESTART")"

banner "config drives the server, not the unit"
check "port in conf"       "0" "$(hasre '^MUSICBOX_PORT=80$' "$CONF")"
check "mpd host in conf"   "0" "$(hasre '^MUSICBOX_MPD_HOST=127\.0\.0\.1$' "$CONF")"
check "mpd port in conf"   "0" "$(hasre '^MUSICBOX_MPD_PORT=6600$' "$CONF")"
check "web root in conf"   "0" "$(hasre '^MUSICBOX_WEB_ROOT=.*/frontend$' "$CONF")"
check "unit hardcodes no port" "1" "$(hasre '^Environment=MUSICBOX_PORT' "$UNIT")"

banner "flags change the generated output"
bash "$SCRIPT" --emit "$WORK/alt" --port 8080 --mpd-host nas.local --user pi \
    --deploy-dir /opt/mb >/dev/null 2>&1
check "--port honoured"       "0" "$(hasre '^MUSICBOX_PORT=8080$' "$WORK/alt/server.conf")"
check "--mpd-host honoured"   "0" "$(hasre '^MUSICBOX_MPD_HOST=nas\.local$' "$WORK/alt/server.conf")"
check "--user honoured"       "0" "$(hasre '^User=pi$' "$WORK/alt/musicbox-server.service")"
check "--deploy-dir honoured" "0" "$(hasre '^ExecStart=/usr/bin/node /opt/mb/backend/server\.js$' "$WORK/alt/musicbox-server.service")"
check "path unit follows deploy-dir" "0" "$(hasre '^PathChanged=/opt/mb/backend/server\.js$' "$WORK/alt/musicbox-server.path")"

banner "the kiosk waits for the server and points at it"
KOUT="$WORK/kiosk"
bash "$KIOSK" --emit "$KOUT" --hostname testbox >/dev/null 2>&1
check "kiosk emit exits 0" "0" "$?"
check "kiosk ordered after the server" "0" \
    "$(hasre '^After=musicbox-server\.service$' "$KOUT/musicbox-kiosk.service")"
# Wants, not Requires: a broken server should still leave a panel that says so.
check "kiosk Wants (not Requires) the server" "0" \
    "$(hasre '^Wants=musicbox-server\.service$' "$KOUT/musicbox-kiosk.service")"
check "kiosk does not hard-require it" "1" \
    "$(hasre '^Requires=musicbox-server\.service$' "$KOUT/musicbox-kiosk.service")"
check "KIOSK_URL points at the web UI" "0" \
    "$(hasre '^KIOSK_URL="http://localhost/"$' "$KOUT/kiosk.conf")"
check "no longer the holding page" "1" "$(hasre '^KIOSK_URL="file://' "$KOUT/kiosk.conf")"
check "wrapper default matches" "0" "$(has 'KIOSK_URL:-http://localhost/' "$KOUT/musicbox-kiosk")"
check "MPD still owns the DAC" "0" "$(has '--mute-audio' "$KOUT/musicbox-kiosk")"

banner "it configures, it does not install"
check "no apt-get in setup-server.sh" "1" "$(has 'apt-get install' "$SCRIPT")"
check "points at install.sh when node is missing" "0" "$(has 'run install.sh first' "$SCRIPT")"
check "install.sh installs nodejs" "0" "$(hasre '^[[:space:]]+nodejs[[:space:]]' "$REPO/install/install.sh")"
check "install.sh does NOT install npm" "1" "$(hasre '^[[:space:]]+npm[[:space:]]' "$REPO/install/install.sh")"
check "the npm package-count reason is recorded" "0" "$(has '363' "$REPO/install/install.sh")"

banner "idempotency and CLI"
sum1="$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit "$OUT" >/dev/null 2>&1
check "re-emitting is byte-identical" "$sum1" "$(cat "$OUT"/* | md5sum)"
bash "$SCRIPT" --emit >/dev/null 2>&1
check "--emit without a destination fails" "1" "$?"
bash "$SCRIPT" --bogus >/dev/null 2>&1
check "unknown option fails" "1" "$?"
bash "$SCRIPT" --help >/dev/null 2>&1
check "--help exits 0" "0" "$?"
check "--help mentions --revert" "0" "$(bash "$SCRIPT" --help 2>/dev/null | grep -q -- '--revert'; echo $?)"

banner "the dev loop exists and needs no sudo"
check "dev-push.sh present"   "0" "$(if [[ -x "$REPO/tools/dev-push.sh" ]]; then echo 0; else echo 1; fi)"
check "build.sh present"      "0" "$(if [[ -x "$REPO/tools/build.sh" ]]; then echo 0; else echo 1; fi)"
check "dev-push uses rsync"   "0" "$(has 'rsync -a' "$REPO/tools/dev-push.sh")"
# --inplace would overwrite the watched file in place and break the .path
# trigger. The string appears in a comment explaining that, so check the actual
# rsync invocations rather than the whole file.
check "no rsync invocation uses --inplace" "1" \
    "$(grep -E '^[[:space:]]*rsync ' "$REPO/tools/dev-push.sh" | grep -q -- '--inplace'; echo $?)"
# "sudo" appears in a comment and in an apt hint; what must not exist is an
# actual sudo invocation, which would put a password prompt in the inner loop.
check "sudo is never invoked" "1" \
    "$(grep -qE '^[[:space:]]*sudo ' "$REPO/tools/dev-push.sh"; echo $?)"
check "dev-push never builds on the device" "1" "$(has 'ssh.*npm' "$REPO/tools/dev-push.sh")"

printf '\n===============================\n passed: %d   failed: %d\n===============================\n' "$PASS" "$FAIL"
[[ "$FAIL" -eq 0 ]]
