#!/usr/bin/env bash
#
# musicbox — setup-cd.sh
#
# Plays audio CDs from the USB drive: MPD reads the disc through its cdio_paranoia
# input, and a small helper tells the web server when a disc is in the drive and
# ejects it on request.
#
# Run order:
#   setup.sh -> setup-hardware.sh -> install.sh -> setup-nas.sh -> setup-mpd.sh
#   -> setup-server.sh -> setup-bluetooth.sh -> setup-cd.sh -> setup-kiosk.sh
#
# THIS SCRIPT INSTALLS NOTHING. eject and mpc come from install.sh; udevadm is
# part of the base image.
#
# MPD PLAYS THE DISC, so MPD stays the only thing that ever opens hw:0,0 and the
# Bluetooth arbiter's existing "MPD started playing" handoff covers CDs too. All
# MPD needs is to be in the cdrom group. See .claude/docs/cd.md.
#
# Usage:
#   sudo ./setup-cd.sh --dry-run
#   sudo ./setup-cd.sh
#   sudo ./setup-cd.sh --revert
#
#   ./setup-cd.sh --emit DEST
#       Write every generated artifact to a directory and exit. Touches no system
#       state, needs no root; used by the tests and handy for review.

set -euo pipefail

readonly SCRIPT_VERSION="1.0.0"

readonly HELPER_BIN="/usr/local/bin/musicbox-cd"
readonly HELPER_UNIT="/etc/systemd/system/musicbox-cd.service"

# Its own directory: /run/musicbox belongs to musicbox-bt-monitor's
# RuntimeDirectory, and two units owning one directory is the dead-inode trap.
# Must match DEFAULT_CD_STATE_PATH in src/backend/src/cd.ts; the tests check.
readonly RUN_DIR="/run/musicbox-cd"
readonly STATE_FILE="${RUN_DIR}/cd.json"
readonly CONTROL_FIFO="${RUN_DIR}/control"

readonly APP_USER="musicbox"
readonly MPD_USER="mpd"
readonly CD_GROUP="cdrom"

# udev's stable name for the first optical drive.
readonly CD_DEVICE="/dev/cdrom"

DRY_RUN=0
ASSUME_YES=0
MODE="apply"

if [[ -t 1 ]]; then
    C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'
    C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_BLUE=$'\033[34m'
else
    C_RESET=""; C_BOLD=""; C_DIM=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_BLUE=""
fi

phase() { printf '\n%s==> %s%s\n' "${C_BOLD}${C_BLUE}" "$*" "${C_RESET}"; }
log()   { printf '    %s\n' "$*"; }
ok()    { printf '    %s+%s %s\n' "${C_GREEN}" "${C_RESET}" "$*"; }
skip()  { printf '    %s.%s %s\n' "${C_DIM}" "${C_RESET}" "${C_DIM}$*${C_RESET}"; }
warn()  { printf '    %s!%s %s\n' "${C_YELLOW}" "${C_RESET}" "$*" >&2; }
die()   { printf '\n%sERROR:%s %s\n' "${C_RED}${C_BOLD}" "${C_RESET}" "$*" >&2; exit 1; }
dry()   { [[ "$DRY_RUN" -eq 1 ]]; }

run() {
    if dry; then printf '    %s[dry-run]%s %s\n' "${C_DIM}" "${C_RESET}" "$*"
    else "$@"; fi
}

usage() { sed -n '3,27p' "$0" | sed 's/^# \{0,1\}//'; }

require_root() { [[ "$(id -u)" -eq 0 ]] || die "this needs root — run with sudo"; }

# install_if_changed <tmp> <dest> [mode] -> 0 changed, 1 already current
install_if_changed() {
    local tmp="$1" dest="$2" mode="${3:-0644}"
    if cmp -s "$tmp" "$dest" 2>/dev/null; then
        rm -f "$tmp"; return 1
    fi
    if dry; then
        printf '    %s[dry-run]%s would write %s\n' "${C_DIM}" "${C_RESET}" "$dest"
        rm -f "$tmp"; return 0
    fi
    install -D -m "$mode" "$tmp" "$dest"
    rm -f "$tmp"
    return 0
}

in_group() { id -nG "$1" 2>/dev/null | tr ' ' '\n' | grep -qx "$2"; }

# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

gen_helper_unit() {
    cat <<UNIT
[Unit]
Description=musicbox CD drive watcher
Documentation=https://github.com/LukeMcDonnell/pi-musicbox
# Not ordered after musicbox-server and not wanted by it: the server only reads
# what this publishes.
After=systemd-udevd.service mpd.service

[Service]
Type=simple
ExecStart=${HELPER_BIN} monitor
Restart=always
RestartSec=2
# Needs no root: udev events are readable by anyone and eject needs only cdrom.
User=${APP_USER}
Group=${APP_USER}
SupplementaryGroups=${CD_GROUP}

# Preserved so the server's inotify watch on the directory survives a restart.
RuntimeDirectory=musicbox-cd
RuntimeDirectoryMode=0755
RuntimeDirectoryPreserve=yes

StandardOutput=journal
StandardError=journal
SyslogIdentifier=musicbox-cd

[Install]
WantedBy=multi-user.target
UNIT
}

gen_helper() {
    # Unquoted preamble for the paths only; everything else is a quoted heredoc so
    # the shell cannot execute anything in it at emit time.
    cat <<PREAMBLE
#!/usr/bin/env bash
#
# musicbox-cd — publishes whether an audio CD is in the drive, and ejects it.
#
# Generated by install/setup-cd.sh. Do not edit here; edit the generator.
#
STATE_FILE="${STATE_FILE}"
CONTROL_FIFO="${CONTROL_FIFO}"
RUN_DIR="${RUN_DIR}"
CD_DEVICE="${CD_DEVICE}"
PREAMBLE
    cat <<'HELPER'

# No set -e: a long-lived loop over commands that fail transiently.
set -uo pipefail

LAST_PUBLISHED=""

log() { printf 'musicbox-cd: %s\n' "$*"; }

# By rename, so the server never reads a half-written file.
publish_raw() {
    local body="$1" tmp
    [[ "$body" == "$LAST_PUBLISHED" ]] && return 0
    mkdir -p "$RUN_DIR" 2>/dev/null
    tmp="${STATE_FILE}.tmp"
    printf '%s\n' "$body" > "$tmp" 2>/dev/null || { log "cannot write ${tmp}"; return 1; }
    chmod 0644 "$tmp" 2>/dev/null
    mv -f "$tmp" "$STATE_FILE" 2>/dev/null || { log "cannot publish ${STATE_FILE}"; return 1; }
    LAST_PUBLISHED="$body"
    log "published ${body}"
}

audio_tracks() {
    udevadm info -q property -n "$CD_DEVICE" 2>/dev/null \
        | sed -n 's/^ID_CDROM_MEDIA_TRACK_COUNT_AUDIO=\([0-9][0-9]*\)$/\1/p' | head -1
}

# Asks udev rather than the event: the tray-close event arrives before the disc
# has been read, and a later change event carries the track counts.
refresh() {
    local tracks
    tracks="$(audio_tracks)"
    if [[ -n "$tracks" && "$tracks" -gt 0 ]]; then
        publish_raw "{\"present\":true,\"tracks\":${tracks}}"
    else
        publish_raw '{"present":false}'
    fi
}

stop_mpd_if_cd() {
    local file
    file="$(mpc current -f '%file%' 2>/dev/null)"
    [[ "$file" == cdda://* ]] || return 0
    log "stopping MPD: it is playing the disc"
    mpc -q stop >/dev/null 2>&1
}

do_eject() {
    stop_mpd_if_cd
    eject "$CD_DEVICE" >/dev/null 2>&1 || log "eject ${CD_DEVICE} failed"
    refresh
}

# One property line from udevadm monitor.
handle_udev() {
    case "$1" in
        # The stock 60-cdrom_id.rules already ejects on the button, so only MPD
        # is ours to deal with.
        DISK_EJECT_REQUEST=1) stop_mpd_if_cd ;;
        DEVNAME=/dev/sr*)     refresh ;;
    esac
}

# A closed set, matching CD_CONTROL_VERBS in src/backend/src/cd.ts.
handle_ctl() {
    case "$1" in
        eject) do_eject ;;
        *)     log "ignoring unknown control verb: $1" ;;
    esac
}

feed() {
    local tag="$1"; shift
    while :; do
        "$@" 2>/dev/null | while IFS= read -r line; do
            [[ -n "$line" ]] && printf '%s %s\n' "$tag" "$line"
        done
        sleep 2
    done
}

do_monitor() {
    local fifo
    fifo="$(mktemp -u "${TMPDIR:-/tmp}/musicbox-cd.XXXXXX")"
    mkfifo "$fifo" || { log "cannot create ${fifo}"; exit 1; }

    rm -f "$CONTROL_FIFO"
    mkdir -p "$RUN_DIR" 2>/dev/null
    if mkfifo -m 0620 "$CONTROL_FIFO" 2>/dev/null; then
        # Held open by us so `cat` never sees EOF between commands.
        exec 9<>"$CONTROL_FIFO"
    else
        log "WARNING: could not create ${CONTROL_FIFO}; eject from the web UI will not work"
    fi

    # Removed, not set to "no disc": a restart must read as unknown, or the server
    # would take the next publish for an insertion and start playing.
    # shellcheck disable=SC2064
    trap "rm -f '$fifo' '$CONTROL_FIFO' '$STATE_FILE'" EXIT

    refresh
    log "watching ${CD_DEVICE}"

    feed udev udevadm monitor --udev --property --subsystem-match=block > "$fifo" &
    feed ctl  cat "$CONTROL_FIFO"                                      > "$fifo" &

    local tag rest
    while IFS=' ' read -r tag rest; do
        case "$tag" in
            udev) handle_udev "$rest" ;;
            ctl)  handle_ctl  "$rest" ;;
        esac
    done < "$fifo"
}

main() {
    case "${1:-help}" in
        monitor) do_monitor ;;
        status)  cat "$STATE_FILE" 2>/dev/null || printf '{}\n' ;;
        eject)   do_eject ;;
        *)       printf 'usage: musicbox-cd {monitor|status|eject}\n' ;;
    esac
}

main "$@"
HELPER
}

# ---------------------------------------------------------------------------
# Emit mode — no root, no system state, exactly the generators used by do_apply
# ---------------------------------------------------------------------------

emit_all() {
    local dest="$1"
    mkdir -p "$dest"
    gen_helper      > "${dest}/musicbox-cd"
    gen_helper_unit > "${dest}/musicbox-cd.service"
    chmod 0755 "${dest}/musicbox-cd"
    printf '  wrote musicbox-cd musicbox-cd.service -> %s\n' "$dest"
}

# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

do_apply() {
    require_root

    phase "Preflight"
    local cmd
    for cmd in eject mpc udevadm; do
        command -v "$cmd" >/dev/null 2>&1 || die "${cmd} is not installed — run install.sh first"
    done
    ok "eject, mpc and udevadm present"
    id "$MPD_USER" >/dev/null 2>&1 || die "no ${MPD_USER} user — run install.sh and setup-mpd.sh first"
    id "$APP_USER" >/dev/null 2>&1 || die "no ${APP_USER} user — the helper runs as it"
    if [[ -e "$CD_DEVICE" ]]; then
        ok "${CD_DEVICE} present"
    else
        warn "no ${CD_DEVICE} — is the drive plugged in? The helper will wait for it."
        warn "check: lsblk"
    fi

    phase "Permissions"
    local mpd_changed=0
    if in_group "$MPD_USER" "$CD_GROUP"; then
        skip "${MPD_USER} already in ${CD_GROUP}"
    else
        run usermod -aG "$CD_GROUP" "$MPD_USER"
        dry || ok "${MPD_USER} added to ${CD_GROUP} — it opens the drive"
        mpd_changed=1
    fi
    in_group "$APP_USER" "$CD_GROUP" || warn "${APP_USER} is not in ${CD_GROUP}; the unit adds it for the helper"

    phase "Helper"
    local tmp changed=0
    tmp="$(mktemp)"; gen_helper > "$tmp"
    if install_if_changed "$tmp" "$HELPER_BIN" 0755; then ok "$HELPER_BIN"; changed=1
    else skip "$HELPER_BIN already current"; fi

    tmp="$(mktemp)"; gen_helper_unit > "$tmp"
    if install_if_changed "$tmp" "$HELPER_UNIT" 0644; then ok "$HELPER_UNIT"; changed=1
    else skip "$HELPER_UNIT already current"; fi

    phase "Enabling"
    if dry; then
        printf '    %s[dry-run]%s would enable musicbox-cd.service and restart mpd if its groups changed\n' \
            "${C_DIM}" "${C_RESET}"
        printf '\n    %sDry run — nothing was changed.%s\n' "${C_BOLD}" "${C_RESET}"
        return 0
    fi

    systemctl daemon-reload
    systemctl enable musicbox-cd.service >/dev/null 2>&1 || true
    if (( changed )) || ! systemctl is-active --quiet musicbox-cd.service; then
        systemctl restart musicbox-cd.service >/dev/null 2>&1 \
            || warn "musicbox-cd failed — check: journalctl -u musicbox-cd -b"
        ok "musicbox-cd running"
    else
        skip "musicbox-cd unchanged — left running"
    fi

    # MPD picks up a new group only at startup, so this interrupts playback once.
    if (( mpd_changed )); then
        systemctl restart mpd.service >/dev/null 2>&1 || warn "mpd failed to restart"
        ok "mpd restarted to pick up ${CD_GROUP}"
    else
        skip "mpd left alone"
    fi

    phase "Result"
    log "Disc state:   ${HELPER_BIN} status"
    log "Watch it:     journalctl -u musicbox-cd -f"
}

# ---------------------------------------------------------------------------
# Revert
# ---------------------------------------------------------------------------

do_revert() {
    require_root
    phase "Removing CD playback"

    if systemctl list-unit-files musicbox-cd.service >/dev/null 2>&1; then
        run systemctl disable --now musicbox-cd.service >/dev/null 2>&1 || true
    fi
    run rm -f "$HELPER_BIN" "$HELPER_UNIT" "$STATE_FILE" "$CONTROL_FIFO"
    run rmdir "$RUN_DIR" 2>/dev/null || true
    run systemctl daemon-reload
    ok "helper and unit removed"

    if in_group "$MPD_USER" "$CD_GROUP"; then
        run gpasswd -d "$MPD_USER" "$CD_GROUP" >/dev/null
        run systemctl restart mpd.service >/dev/null 2>&1 || true
        ok "${MPD_USER} removed from ${CD_GROUP}; mpd restarted"
    else
        skip "${MPD_USER} not in ${CD_GROUP}"
    fi
    log "packages were left installed"
}

main() {
    local dest=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)  DRY_RUN=1 ;;
            -y|--yes)   ASSUME_YES=1 ;;
            --revert)   MODE="revert" ;;
            --emit)     MODE="emit"; dest="${2:-}"; shift ;;
            -h|--help)  usage; exit 0 ;;
            *)          usage >&2; die "unknown option: $1" ;;
        esac
        shift
    done
    : "$ASSUME_YES"

    case "$MODE" in
        emit)
            [[ -n "$dest" ]] || die "--emit needs a destination directory"
            emit_all "$dest"
            ;;
        revert)
            printf '%smusicbox setup-cd.sh %s%s\n' "${C_BOLD}" "${SCRIPT_VERSION}" "${C_RESET}"
            dry && printf '%sDRY RUN — no changes will be made%s\n' "${C_YELLOW}" "${C_RESET}"
            do_revert
            ;;
        *)
            printf '%smusicbox setup-cd.sh %s%s\n' "${C_BOLD}" "${SCRIPT_VERSION}" "${C_RESET}"
            dry && printf '%sDRY RUN — no changes will be made%s\n' "${C_YELLOW}" "${C_RESET}"
            do_apply
            ;;
    esac
}

main "$@"
